# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Contact")

model.instance <- Contact$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("elementType", {
  # tests for the property `elementType` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`elementType`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # The contact&#39;s name.

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("affiliation", {
  # tests for the property `affiliation` (character)
  # The contact&#39;s affiliation.

  # uncomment below to test the property 
  #expect_equal(model.instance$`affiliation`, "EXPECTED_RESULT")
})

test_that("email", {
  # tests for the property `email` (character)
  # The contact&#39;s e-mail address.

  # uncomment below to test the property 
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

