# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SmallMoleculeEvidence")

model.instance <- SmallMoleculeEvidence$new()

test_that("prefix", {
  # tests for the property `prefix` (character)
  # The small molecule evidence table row prefix. SME MUST be used for rows of the small molecule evidence table.

  # uncomment below to test the property 
  #expect_equal(model.instance$`prefix`, "EXPECTED_RESULT")
})

test_that("header_prefix", {
  # tests for the property `header_prefix` (character)
  # The small molecule evidence table header prefix. SEH MUST be used for the small molecule evidence table header line (the column labels).

  # uncomment below to test the property 
  #expect_equal(model.instance$`header_prefix`, "EXPECTED_RESULT")
})

test_that("sme_id", {
  # tests for the property `sme_id` (integer)
  # A within file unique identifier for the small molecule evidence result.

  # uncomment below to test the property 
  #expect_equal(model.instance$`sme_id`, "EXPECTED_RESULT")
})

test_that("evidence_input_id", {
  # tests for the property `evidence_input_id` (character)
  # A within file unique identifier for the input data used to support this identification e.g. fragment spectrum, RT and m/z pair, isotope profile that was used for the identification process, to serve as a grouping mechanism, whereby multiple rows of results from the same input data share the same ID. The identifiers may be human readable but should not be assumed to be interpretable. For example, if fragmentation spectra have been searched then the ID may be the spectrum reference, or for accurate mass search, the ms_run[2]:458.75.

  # uncomment below to test the property 
  #expect_equal(model.instance$`evidence_input_id`, "EXPECTED_RESULT")
})

test_that("database_identifier", {
  # tests for the property `database_identifier` (character)
  # The putative identification for the small molecule sourced from an external database, using the same prefix specified in database[1-n]-prefix.  This could include additionally a chemical class or an identifier to a spectral library entity, even if its actual identity is unknown.  For the “no database” case, \&quot;null\&quot; must be used. The unprefixed use of \&quot;null\&quot; is prohibited for any other case. If no putative identification can be reported for a particular database, it MUST be reported as the database prefix followed by null. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`database_identifier`, "EXPECTED_RESULT")
})

test_that("chemical_formula", {
  # tests for the property `chemical_formula` (character)
  # The chemical formula of the identified compound e.g. in a database, assumed to match the theoretical mass to charge (in some cases this will be the derivatized form, including adducts and protons).  This should be specified in Hill notation (EA Hill 1900), i.e. elements in the order C, H and then alphabetically all other elements. Counts of one may be omitted. Elements should be capitalized properly to avoid confusion (e.g., “CO” vs. “Co”). The chemical formula reported should refer to the neutral form. Charge state is reported by the charge field.  Example N-acetylglucosamine would be encoded by the string “C8H15NO6” 

  # uncomment below to test the property 
  #expect_equal(model.instance$`chemical_formula`, "EXPECTED_RESULT")
})

test_that("smiles", {
  # tests for the property `smiles` (character)
  # The potential molecule’s structure in the simplified molecular-input line-entry system (SMILES) for the small molecule.

  # uncomment below to test the property 
  #expect_equal(model.instance$`smiles`, "EXPECTED_RESULT")
})

test_that("inchi", {
  # tests for the property `inchi` (character)
  # A standard IUPAC International Chemical Identifier (InChI) for the given substance.

  # uncomment below to test the property 
  #expect_equal(model.instance$`inchi`, "EXPECTED_RESULT")
})

test_that("chemical_name", {
  # tests for the property `chemical_name` (character)
  # The small molecule’s chemical/common name, or general description if a chemical name is unavailable.

  # uncomment below to test the property 
  #expect_equal(model.instance$`chemical_name`, "EXPECTED_RESULT")
})

test_that("uri", {
  # tests for the property `uri` (character)
  # A URI pointing to the small molecule’s entry in a database (e.g., the small molecule’s HMDB, Chebi or KEGG entry).

  # uncomment below to test the property 
  #expect_equal(model.instance$`uri`, "EXPECTED_RESULT")
})

test_that("derivatized_form", {
  # tests for the property `derivatized_form` (Parameter)

  # uncomment below to test the property 
  #expect_equal(model.instance$`derivatized_form`, "EXPECTED_RESULT")
})

test_that("adduct_ion", {
  # tests for the property `adduct_ion` (character)
  # The assumed classification of this molecule’s adduct ion after detection, following the general style in the 2013 IUPAC recommendations on terms relating to MS e.g. [M+H]+, [M+Na]1+, [M+NH4]1+, [M-H]1-, [M+Cl]1-. If the adduct classification is ambiguous with regards to identification evidence it MAY be null.

  # uncomment below to test the property 
  #expect_equal(model.instance$`adduct_ion`, "EXPECTED_RESULT")
})

test_that("exp_mass_to_charge", {
  # tests for the property `exp_mass_to_charge` (numeric)
  # The experimental mass/charge value for the precursor ion. If multiple adduct forms have been combined into a single identification event/search, then a single value e.g. for the protonated form SHOULD be reported here.

  # uncomment below to test the property 
  #expect_equal(model.instance$`exp_mass_to_charge`, "EXPECTED_RESULT")
})

test_that("charge", {
  # tests for the property `charge` (integer)
  # The small molecule evidence’s charge value using positive integers both for positive and negative polarity modes.

  # uncomment below to test the property 
  #expect_equal(model.instance$`charge`, "EXPECTED_RESULT")
})

test_that("theoretical_mass_to_charge", {
  # tests for the property `theoretical_mass_to_charge` (numeric)
  # The theoretical mass/charge value for the small molecule or the database mass/charge value (for a spectral library match).

  # uncomment below to test the property 
  #expect_equal(model.instance$`theoretical_mass_to_charge`, "EXPECTED_RESULT")
})

test_that("spectra_ref", {
  # tests for the property `spectra_ref` (array[SpectraRef])
  # Reference to a spectrum in a spectrum file, for example a fragmentation spectrum has been used to support the identification. If a separate spectrum file has been used for fragmentation spectrum, this MUST be reported in the metadata section as additional ms_runs. The reference must be in the format ms_run[1-n]:{SPECTRA_REF} where SPECTRA_REF MUST follow the format defined in 5.2 (including references to chromatograms where these are used to inform identification). Multiple spectra MUST be referenced using a “|” delimited list for the (rare) cases in which search engines have combined or aggregated multiple spectra in advance of the search to make identifications.  If a fragmentation spectrum has not been used, the value should indicate the ms_run to which is identification is mapped e.g. “ms_run[1]”. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`spectra_ref`, "EXPECTED_RESULT")
})

test_that("identification_method", {
  # tests for the property `identification_method` (Parameter)

  # uncomment below to test the property 
  #expect_equal(model.instance$`identification_method`, "EXPECTED_RESULT")
})

test_that("ms_level", {
  # tests for the property `ms_level` (Parameter)

  # uncomment below to test the property 
  #expect_equal(model.instance$`ms_level`, "EXPECTED_RESULT")
})

test_that("id_confidence_measure", {
  # tests for the property `id_confidence_measure` (array[numeric])
  # Any statistical value or score for the identification. The metadata section reports the type of score used, as id_confidence_measure[1-n] of type Param.

  # uncomment below to test the property 
  #expect_equal(model.instance$`id_confidence_measure`, "EXPECTED_RESULT")
})

test_that("rank", {
  # tests for the property `rank` (integer)
  # The rank of this identification from this approach as increasing integers from 1 (best ranked identification). Ties (equal score) are represented by using the same rank – defaults to 1 if there is no ranking system used.

  # uncomment below to test the property 
  #expect_equal(model.instance$`rank`, "EXPECTED_RESULT")
})

test_that("opt", {
  # tests for the property `opt` (array[OptColumnMapping])
  # Additional columns can be added to the end of the small molecule evidence table. These column headers MUST start with the prefix “opt_” followed by the {identifier} of the object they reference: assay, study variable, MS run or “global” (if the value relates to all replicates). Column names MUST only contain the following characters: ‘A’-‘Z’, ‘a’-‘z’, ‘0’-‘9’, ‘’, ‘-’, ‘[’, ‘]’, and ‘:’. CV parameter accessions MAY be used for optional columns following the format: opt{identifier}_cv_{accession}_\\{parameter name}. Spaces within the parameter’s name MUST be replaced by ‘_’. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`opt`, "EXPECTED_RESULT")
})

test_that("comment", {
  # tests for the property `comment` (array[Comment])

  # uncomment below to test the property 
  #expect_equal(model.instance$`comment`, "EXPECTED_RESULT")
})

