# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Publication")

model.instance <- Publication$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("publicationItems", {
  # tests for the property `publicationItems` (array[PublicationItem])
  # The publication item ids referenced by this publication.

  # uncomment below to test the property 
  #expect_equal(model.instance$`publicationItems`, "EXPECTED_RESULT")
})

