# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PublicationAllOf")

model.instance <- PublicationAllOf$new()

test_that("publicationItems", {
  # tests for the property `publicationItems` (array[PublicationItem])
  # The publication item ids referenced by this publication.

  # uncomment below to test the property 
  #expect_equal(model.instance$`publicationItems`, "EXPECTED_RESULT")
})

