# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UriAllOf")

model.instance <- UriAllOf$new()

test_that("value", {
  # tests for the property `value` (character)
  # The URI pointing to the external resource.

  # uncomment below to test the property 
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

