# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Software")

model.instance <- Software$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("elementType", {
  # tests for the property `elementType` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`elementType`, "EXPECTED_RESULT")
})

test_that("parameter", {
  # tests for the property `parameter` (Parameter)

  # uncomment below to test the property 
  #expect_equal(model.instance$`parameter`, "EXPECTED_RESULT")
})

test_that("setting", {
  # tests for the property `setting` (array[character])
  # A software setting used. This field MAY occur multiple times for a single software. The value of this field is deliberately set as a String, since there currently do not exist cvParams for every possible setting. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`setting`, "EXPECTED_RESULT")
})

