# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Metadata")

model.instance <- Metadata$new()

test_that("prefix", {
  # tests for the property `prefix` (character)
  # The metadata section prefix. MUST always be MTD. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`prefix`, "EXPECTED_RESULT")
})

test_that("mzTab-version", {
  # tests for the property `mzTab-version` (character)
  # The version of the mzTab file. The suffix MUST be \&quot;-M\&quot; for mzTab for metabolomics (mzTab-M). 

  # uncomment below to test the property 
  #expect_equal(model.instance$`mzTab-version`, "EXPECTED_RESULT")
})

test_that("mzTab-ID", {
  # tests for the property `mzTab-ID` (character)
  # The ID of the mzTab file, this could be supplied by the repository from which it is downloaded or a local identifier from the lab producing the file. It is not intended to be a globally unique ID but carry some locally useful meaning. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`mzTab-ID`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)
  # The file’s human readable title. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # The file’s human readable description. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("sample_processing", {
  # tests for the property `sample_processing` (array[SampleProcessing])
  # A list of parameters describing a sample processing, preparation or handling step similar to a biological or analytical methods report. The order of the sample_processing items should reflect the order these processing steps were performed in. If multiple parameters are given for a step these MUST be separated by a “|”. If derivatization was performed, it MUST be reported here as a general step, e.g. &#39;silylation&#39; and the actual derivatization agens MUST be specified in the Section 6.2.54 part. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`sample_processing`, "EXPECTED_RESULT")
})

test_that("instrument", {
  # tests for the property `instrument` (array[Instrument])
  # The name, source, analyzer and detector of the instruments used in the experiment. Multiple instruments are numbered [1-n].

  # uncomment below to test the property 
  #expect_equal(model.instance$`instrument`, "EXPECTED_RESULT")
})

test_that("software", {
  # tests for the property `software` (array[Software])
  # Software used to analyze the data and obtain the reported results. The parameter’s value SHOULD contain the software’s version. The order (numbering) should reflect the order in which the tools were used. A software setting used. This field MAY occur multiple times for a single software. The value of this field is deliberately set as a String, since there currently do not exist CV terms for every possible setting.

  # uncomment below to test the property 
  #expect_equal(model.instance$`software`, "EXPECTED_RESULT")
})

test_that("publication", {
  # tests for the property `publication` (array[Publication])
  # A publication associated with this file. Several publications can be given by indicating the number in the square brackets after “publication”. PubMed ids must be prefixed by “pubmed:”, DOIs by “doi:”. Multiple identifiers MUST be separated by “|”.

  # uncomment below to test the property 
  #expect_equal(model.instance$`publication`, "EXPECTED_RESULT")
})

test_that("contact", {
  # tests for the property `contact` (array[Contact])
  # The contact’s name, affiliation and e-mail. Several contacts can be given by indicating the number in the square brackets after \&quot;contact\&quot;. A contact has to be supplied in the format [first name] [initials] [last name].

  # uncomment below to test the property 
  #expect_equal(model.instance$`contact`, "EXPECTED_RESULT")
})

test_that("uri", {
  # tests for the property `uri` (array[Uri])
  # A URI pointing to the file’s source data (e.g., a MetaboLights records).

  # uncomment below to test the property 
  #expect_equal(model.instance$`uri`, "EXPECTED_RESULT")
})

test_that("external_study_uri", {
  # tests for the property `external_study_uri` (array[Uri])
  # A URI pointing to an external file with more details about the study design (e.g., an ISA-TAB file).

  # uncomment below to test the property 
  #expect_equal(model.instance$`external_study_uri`, "EXPECTED_RESULT")
})

test_that("quantification_method", {
  # tests for the property `quantification_method` (Parameter)

  # uncomment below to test the property 
  #expect_equal(model.instance$`quantification_method`, "EXPECTED_RESULT")
})

test_that("study_variable", {
  # tests for the property `study_variable` (array[StudyVariable])
  # Specification of study_variable. (empty) name: A name for each study variable (experimental condition or factor), to serve as a list of the study variables that MUST be reported in the following tables. For software that does not capture study variables, a single study variable MUST be reported, linking to all assays. This single study variable MUST have the identifier “undefined“. assay_refs: Bar-separated references to the IDs of assays grouped in the study variable. average_function: The function used to calculate the study variable quantification value and the operation used is not arithmetic mean (default) e.g. “geometric mean”, “median”. The 1-n refers to different study variables. variation_function: The function used to calculate the study variable quantification variation value if it is reported and the operation used is not coefficient of variation (default) e.g. “standard error”. description: A textual description of the study variable. factors: Additional parameters or factors, separated by bars, that are known about study variables allowing the capture of more complex, such as nested designs. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`study_variable`, "EXPECTED_RESULT")
})

test_that("ms_run", {
  # tests for the property `ms_run` (array[MsRun])
  # Specification of ms_run.  location: Location of the external data file e.g. raw files on which analysis has been performed. If the actual location of the MS run is unknown, a “null” MUST be used as a place holder value, since the [1-n] cardinality is referenced elsewhere. If pre-fractionation has been performed, then [1-n] ms_runs SHOULD be created per assay.  instrument_ref: If different instruments are used in different runs, instrument_ref can be used to link a specific instrument to a specific run.  format: Parameter specifying the data format of the external MS data file. If ms_run[1-n]-format is present, ms_run[1-n]-id_format SHOULD also be present, following the parameters specified in Table 1.  id_format: Parameter specifying the id format used in the external data file. If ms_run[1-n]-id_format is present, ms_run[1-n]-format SHOULD also be present. fragmentation_method: The type(s) of fragmentation used in a given ms run. scan_polarity: The polarity mode of a given run. Usually only one value SHOULD be given here except for the case of mixed polarity runs. hash: Hash value of the corresponding external MS data file defined in ms_run[1-n]-location. If ms_run[1-n]-hash is present, ms_run[1-n]-hash_method SHOULD also be present. hash_method: A parameter specifying the hash methods used to generate the String in ms_run[1-n]-hash. Specifics of the hash method used MAY follow the definitions of the mzML format. If ms_run[1-n]-hash is present, ms_run[1-n]-hash_method SHOULD also be present. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`ms_run`, "EXPECTED_RESULT")
})

test_that("assay", {
  # tests for the property `assay` (array[Assay])
  # Specification of assay. (empty) name: A name for each assay, to serve as a list of the assays that MUST be reported in the following tables.  custom: Additional custom parameters or values for a given assay.  external_uri: An external reference uri to further information about the assay, for example via a reference to an object within an ISA-TAB file.  sample_ref: An association from a given assay to the sample analysed.  ms_run_ref: An association from a given assay to the source MS run. All assays MUST reference exactly one ms_run unless a workflow with pre-fractionation is being encoded, in which case each assay MUST reference n ms_runs where n fractions have been collected. Multiple assays SHOULD reference the same ms_run to capture multiplexed experimental designs. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`assay`, "EXPECTED_RESULT")
})

test_that("sample", {
  # tests for the property `sample` (array[Sample])
  # Specification of sample. (empty) name: A name for each sample to serve as a list of the samples that MUST be reported in the following tables. Samples MUST be reported if a statistical design is being captured (i.e. bio or tech replicates). If the type of replicates are not known, samples SHOULD NOT be reported.  species: The respective species of the samples analysed. For more complex cases, such as metagenomics, optional columns and userParams should be used.  tissue: The respective tissue(s) of the sample.  cell_type: The respective cell type(s) of the sample.  disease: The respective disease(s) of the sample.  description: A human readable description of the sample.  custom: Custom parameters describing the sample’s additional properties. Dates MUST be provided in ISO-8601 format. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`sample`, "EXPECTED_RESULT")
})

test_that("custom", {
  # tests for the property `custom` (array[Parameter])
  # Any additional parameters describing the analysis reported.

  # uncomment below to test the property 
  #expect_equal(model.instance$`custom`, "EXPECTED_RESULT")
})

test_that("cv", {
  # tests for the property `cv` (array[CV])
  # Specification of controlled vocabularies. label: A string describing the labels of the controlled vocabularies/ontologies used in the mzTab file as a short-hand e.g. \&quot;MS\&quot; for PSI-MS. full_name: A string describing the full names of the controlled vocabularies/ontologies used in the mzTab file. version: A string describing the version of the controlled vocabularies/ontologies used in the mzTab file. uri: A string containing the URIs of the controlled vocabularies/ontologies used in the mzTab file. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`cv`, "EXPECTED_RESULT")
})

test_that("database", {
  # tests for the property `database` (array[Database])
  # Specification of databases. (empty): The description of databases used. For cases, where a known database has not been used for identification, a userParam SHOULD be inserted to describe any identification performed e.g. de novo. If no identification has been performed at all then \&quot;no database\&quot; should be inserted followed by null. prefix: The prefix used in the “identifier” column of data tables. For the “no database” case \&quot;null\&quot; must be used. version: The database version is mandatory where identification has been performed. This may be a formal version number e.g. “1.4.1”, a date of access “2016-10-27” (ISO-8601 format) or “Unknown” if there is no suitable version that can be annotated. uri: The URI to the database. For the “no database” case, \&quot;null\&quot; must be reported. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`database`, "EXPECTED_RESULT")
})

test_that("derivatization_agent", {
  # tests for the property `derivatization_agent` (array[Parameter])
  # A description of derivatization agents applied to small molecules, using userParams or CV terms where possible.

  # uncomment below to test the property 
  #expect_equal(model.instance$`derivatization_agent`, "EXPECTED_RESULT")
})

test_that("small_molecule-quantification_unit", {
  # tests for the property `small_molecule-quantification_unit` (Parameter)

  # uncomment below to test the property 
  #expect_equal(model.instance$`small_molecule-quantification_unit`, "EXPECTED_RESULT")
})

test_that("small_molecule_feature-quantification_unit", {
  # tests for the property `small_molecule_feature-quantification_unit` (Parameter)

  # uncomment below to test the property 
  #expect_equal(model.instance$`small_molecule_feature-quantification_unit`, "EXPECTED_RESULT")
})

test_that("small_molecule-identification_reliability", {
  # tests for the property `small_molecule-identification_reliability` (Parameter)

  # uncomment below to test the property 
  #expect_equal(model.instance$`small_molecule-identification_reliability`, "EXPECTED_RESULT")
})

test_that("id_confidence_measure", {
  # tests for the property `id_confidence_measure` (array[Parameter])
  # The type of small molecule confidence measures or scores MUST be reported as a CV parameter [1-n]. The CV parameter definition should formally state whether the ordering is high to low or vice versa. The order of the scores SHOULD reflect their importance for the identification and be used to determine the identification’s rank.

  # uncomment below to test the property 
  #expect_equal(model.instance$`id_confidence_measure`, "EXPECTED_RESULT")
})

test_that("colunit-small_molecule", {
  # tests for the property `colunit-small_molecule` (array[ColumnParameterMapping])
  # Defines the used unit for a column in the small molecule section. The format of the value has to be \\{column name}&#x3D;\\{Parameter defining the unit}. This field MUST NOT be used to define a unit for quantification columns. The unit used for small molecule quantification values MUST be set in small_molecule-quantification_unit.

  # uncomment below to test the property 
  #expect_equal(model.instance$`colunit-small_molecule`, "EXPECTED_RESULT")
})

test_that("colunit-small_molecule_feature", {
  # tests for the property `colunit-small_molecule_feature` (array[ColumnParameterMapping])
  # Defines the used unit for a column in the small molecule feature section. The format of the value has to be \\{column name}&#x3D;\\{Parameter defining the unit}. This field MUST NOT be used to define a unit for quantification columns. The unit used for small molecule quantification values MUST be set in small_molecule_feature-quantification_unit.

  # uncomment below to test the property 
  #expect_equal(model.instance$`colunit-small_molecule_feature`, "EXPECTED_RESULT")
})

test_that("colunit-small_molecule_evidence", {
  # tests for the property `colunit-small_molecule_evidence` (array[ColumnParameterMapping])
  # Defines the used unit for a column in the small molecule evidence section. The format of the value has to be \\{column name}&#x3D;\\{Parameter defining the unit}.

  # uncomment below to test the property 
  #expect_equal(model.instance$`colunit-small_molecule_evidence`, "EXPECTED_RESULT")
})

