# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PublicationItem")

model.instance <- PublicationItem$new()

test_that("type", {
  # tests for the property `type` (character)
  # The type qualifier of this publication item.

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("accession", {
  # tests for the property `accession` (character)
  # The native accession id for this publication item.

  # uncomment below to test the property 
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

