context("test-write_mztab_json.R")

test_that("reading and writing of mztab json works", {
  testfile <- system.file("testdata", c("lipidomics-example.mzTab.json"),package="rmztab")
  mzTabObject <- MzTab$new()
  mzTabObject$fromJSON(testfile)
  #print(mzTabObject$toJSONString())
  expect_false(is.null(mzTabObject$metadata))
  expect_false(is.null(mzTabObject$smallMoleculeSummary))
  expect_false(is.null(mzTabObject$smallMoleculeFeature))
  expect_false(is.null(mzTabObject$smallMoleculeEvidence))
  expect_equal(object = mzTabObject$`metadata`$`mzTab-ID`, "ISAS-2018-1234")
  expect_length(mzTabObject$`smallMoleculeSummary`,1)
  expect_length(mzTabObject$`smallMoleculeFeature`,4)
  expect_length(mzTabObject$`smallMoleculeEvidence`,4)
  json <- jsonlite::toJSON(mzTabObject$toJSON(), digits = 10, auto_unbox = TRUE, null = 'null', na = 'null')
  #json <- gsub("NA","\"null\"", json)
  #cat(json)
  tmpfile <- file.path("/","tmp","rmztab-test-write_mztab_json.mzTab")
  write(json, tmpfile)
  mzTabObject2 <- MzTab$new()
  mzTabObject2$fromJSON(tmpfile)
  expect_false(is.null(mzTabObject2$metadata))
  expect_false(is.null(mzTabObject2$smallMoleculeSummary))
  expect_false(is.null(mzTabObject2$smallMoleculeFeature))
  expect_false(is.null(mzTabObject2$smallMoleculeEvidence))
  cat(mzTabObject2$toJSONString())
  expect_equal(object = mzTabObject2$`metadata`$`mzTab-ID`, "ISAS-2018-1234")
  expect_length(mzTabObject2$`smallMoleculeSummary`,1)
  expect_length(mzTabObject2$`smallMoleculeFeature`,4)
  expect_length(mzTabObject2$`smallMoleculeEvidence`,4)
  
})
