# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Database")

model.instance <- Database$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("elementType", {
  # tests for the property `elementType` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`elementType`, "EXPECTED_RESULT")
})

test_that("param", {
  # tests for the property `param` (Parameter)

  # uncomment below to test the property 
  #expect_equal(model.instance$`param`, "EXPECTED_RESULT")
})

test_that("prefix", {
  # tests for the property `prefix` (character)
  # The database prefix.

  # uncomment below to test the property 
  #expect_equal(model.instance$`prefix`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # The database version.

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("uri", {
  # tests for the property `uri` (character)
  # The URI to the online database.

  # uncomment below to test the property 
  #expect_equal(model.instance$`uri`, "EXPECTED_RESULT")
})

