# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Software")

model.instance <- Software$new()

ref.json <- "[{\"id\":1,\"parameter\":{\"cv_label\":\"MS\",\"cv_accession\":\"MS:1000532\",\"name\":\"Xcalibur\",\"value\":\"2.8-280502/2.8.1.2806\"},\"setting\":[\"ScheduledSRMWindow: 2 min\",\"CycleTime: 2 s\"]},{\"id\":2,\"parameter\":{\"cv_label\":\"MS\",\"cv_accession\":\"MS:1000922\",\"name\":\"Skyline\",\"value\":\"3.5.0.9319\"},\"setting\":[\"MSMSmassrange: (50.0, 1800.0)\"]}]"

test_that("software_deserialization_works", {
  software <- jsonlite::fromJSON(ref.json)
  softwareObjects <- ApiClient$new()$deserializeObj(software, "array[Software]", loadNamespace("rmzTabM"))
  #software <- model.instance$fromJSONString(ref)
  expect_false(is.null(software))
  expect_false(is.null(softwareObjects))
  expect_equal(length(softwareObjects), 2)
  expect_equal(softwareObjects[[1]]$id, 1)
  expect_equal(length(softwareObjects[[1]]$setting), 1)
  expect_equal(softwareObjects[[1]]$toJSONString(), "{\"id\":\n          1\n                ,\"parameter\":\n        {\"cv_label\":\"MS\",\"cv_accession\":\"MS:1000532\",\"name\":\"Xcalibur\",\"value\":\"2.8-280502/2.8.1.2806\"}\n        ,\"setting\":\n           [\"ScheduledSRMWindow: 2 min\",\"CycleTime: 2 s\"]\n        }")
})

test_that("software$toDataFrame works", {
  software <- jsonlite::fromJSON(ref.json)
  softwareObjects <- ApiClient$new()$deserializeObj(software, "array[Software]", loadNamespace("rmzTabM"))
  sdf1 <- softwareObjects[[1]]$toDataFrame()
  expect_equal(sdf1[1, "PREFIX"], "MTD")
  expect_equal(sdf1[1, "KEY"], "software[1]")
  expect_equal(sdf1[1, "VALUE"], "[MS, MS:1000532, Xcalibur, 2.8-280502/2.8.1.2806]")
  expect_equal(sdf1[2, "KEY"], "software[1]-setting[1]")
  expect_equal(sdf1[2, "VALUE"], "ScheduledSRMWindow: 2 min")
  expect_equal(sdf1[3, "KEY"], "software[1]-setting[2]")
  expect_equal(sdf1[3, "VALUE"], "CycleTime: 2 s")
  sdf2 <- softwareObjects[[2]]$toDataFrame()
  expect_equal(sdf2[1, "PREFIX"], "MTD")
  expect_equal(sdf2[1, "KEY"], "software[2]")
  expect_equal(sdf2[1, "VALUE"], "[MS, MS:1000922, Skyline, 3.5.0.9319]")
})
