# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ValidatePlainApi")

api.instance <- ValidatePlainApi$new()

test_that("ValidatePlainMzTabFile", {
  # tests for ValidatePlainMzTabFile
  # base path: https://apps.lifs.isas.de/mztabvalidator/rest/v2
  # Validates an mzTab file in plain text representation / tab-separated format and reports syntactic, structural, and semantic errors. 
  # @param character  mztabfile  mzTab file that should be validated. 
  # @param character  level  The level of errors that should be reported, one of ERROR, WARN, INFO.  (optional)
  # @param integer  max.errors  The maximum number of errors to return.  (optional)
  # @param character  semantic.validation  Whether a semantic validation against the default rule set should be performed.  (optional)
  # @return [array[ValidationMessage]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

