# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SpectraRef")

model.instance <- SpectraRef$new()

test_that("ms_run", {
  # tests for the property `ms_run` (MsRun)

  # uncomment below to test the property 
  #expect_equal(model.instance$`ms_run`, "EXPECTED_RESULT")
})

test_that("reference", {
  # tests for the property `reference` (character)
  # The (vendor-dependendent) reference string to the actual mass spectrum. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`reference`, "EXPECTED_RESULT")
})

