# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InstrumentAllOf")

model.instance <- InstrumentAllOf$new()

test_that("name", {
  # tests for the property `name` (Parameter)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("source", {
  # tests for the property `source` (Parameter)

  # uncomment below to test the property 
  #expect_equal(model.instance$`source`, "EXPECTED_RESULT")
})

test_that("analyzer", {
  # tests for the property `analyzer` (array[Parameter])
  # The instrument&#39;s mass analyzer, as defined by the parameter.

  # uncomment below to test the property 
  #expect_equal(model.instance$`analyzer`, "EXPECTED_RESULT")
})

test_that("detector", {
  # tests for the property `detector` (Parameter)

  # uncomment below to test the property 
  #expect_equal(model.instance$`detector`, "EXPECTED_RESULT")
})

