context("test-validate_json_api.R")

test_that("validation via REST API of mztab json works", {
  testfile <- system.file("testdata", c("lipidomics-example.mzTab.json"),package="rmzTabM")
  mzTabObject <- MzTab$new()
  mzTabObject$fromJSON(testfile)
  #expect_false(is.null(mzTabObject$toJSONString()))
  metadataJsonObject <- mzTabObject$`metadata`$toJSON()
  expect_false(is.null(metadataJsonObject))
  #cat(names(metadataJsonObject))
  expect_false(is.null(metadataJsonObject$`mzTab-version`))
  expect_false(is.null(metadataJsonObject$`mzTab-ID`))
  expect_equal("ISAS-2018-1234", metadataJsonObject$`mzTab-ID`)
  expect_false(is.null(metadataJsonObject$`description`))
  #metadataJsonObject$`title`
  expect_false(is.null(metadataJsonObject$`title`))
  expect_true("list" == typeof(metadataJsonObject$`title`))
  expect_true(0 == length(metadataJsonObject$`title`))
  validatePlain <- ValidateApi$new()
  jsonString <- mzTabObject$toJSONString()
  response <- validatePlain$ValidateMzTabFile(mzTabObject, 'info', 50, FALSE)
  expect_false("API server error" == response$content)
  # the next test currently fails, there is an encoding error for description, which should be null in the json but is {}.
  expect_true("API client error" == response$content)
  
  # expect_false(is.null(mzTabObject$metadata))
  # expect_false(is.null(mzTabObject$smallMoleculeSummary))
  # expect_false(is.null(mzTabObject$smallMoleculeFeature))
  # expect_false(is.null(mzTabObject$smallMoleculeEvidence))
  # expect_equal(object = mzTabObject$`metadata`$`mzTab-ID`, "ISAS-2018-1234")
  # expect_length(mzTabObject$`smallMoleculeSummary`,1)
  # expect_length(mzTabObject$`smallMoleculeEvidence`,4)
  # expect_length(mzTabObject$`smallMoleculeFeature`,4)
})
