# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SampleProcessingAllOf")

model.instance <- SampleProcessingAllOf$new()

test_that("sampleProcessing", {
  # tests for the property `sampleProcessing` (array[Parameter])
  # Parameters specifiying sample processing that was applied within one step.

  # uncomment below to test the property 
  #expect_equal(model.instance$`sampleProcessing`, "EXPECTED_RESULT")
})

