# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StudyVariable")

model.instance <- StudyVariable$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # The study variable name.

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("assay_refs", {
  # tests for the property `assay_refs` (array[Assay])
  # The assays referenced by this study variable.

  # uncomment below to test the property 
  #expect_equal(model.instance$`assay_refs`, "EXPECTED_RESULT")
})

test_that("average_function", {
  # tests for the property `average_function` (Parameter)

  # uncomment below to test the property 
  #expect_equal(model.instance$`average_function`, "EXPECTED_RESULT")
})

test_that("variation_function", {
  # tests for the property `variation_function` (Parameter)

  # uncomment below to test the property 
  #expect_equal(model.instance$`variation_function`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # A free-form description of this study variable.

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("factors", {
  # tests for the property `factors` (array[Parameter])
  # Parameters indicating which factors were used for the assays referenced by this study variable, and at which levels.

  # uncomment below to test the property 
  #expect_equal(model.instance$`factors`, "EXPECTED_RESULT")
})

