# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StudyVariable")

model.instance <- StudyVariable$new()

ref.json <- '{
      "id" : 1,
      "name" : "Sphingolipid SRM Quantitation",
      "assay_refs" : [ 1 ],
      "average_function" : {
        "id" : null,
        "cv_label" : "MS",
        "cv_accession" : "MS:1002883",
        "name" : "median",
        "value" : null
      },
      "variation_function" : {
        "id" : null,
        "cv_label" : "MS",
        "cv_accession" : "MS:1002885",
        "name" : "standard error",
        "value" : null
      },
      "description" : "sphingolipid srm quantitation",
      "factors" : null
    }'

test_that("studyVariable", {
  model.instance <- model.instance$fromJSONString(ref.json)
  expect_equal(model.instance$`id`, 1)
  expect_equal(model.instance$`name`, "Sphingolipid SRM Quantitation")
  expect_equal(length(model.instance$`assay_refs`), 1)
  expect_equal(model.instance$`assay_refs`[[1]], 1)
  expect_null(model.instance$`average_function`$id)
  expect_equal(model.instance$`average_function`$cv_label, "MS")
  expect_equal(model.instance$`average_function`$cv_accession, "MS:1002883")
  expect_equal(model.instance$`average_function`$name, "median")
  expect_null(model.instance$`average_function`$value)
  expect_null(model.instance$`variation_function`$id)
  expect_equal(model.instance$`variation_function`$cv_label, "MS")
  expect_equal(model.instance$`variation_function`$cv_accession, "MS:1002885")
  expect_equal(model.instance$`variation_function`$name, "standard error")
  expect_null(model.instance$`variation_function`$value)
  expect_equal(model.instance$`description`, "sphingolipid srm quantitation")
  expect_null(model.instance$`factors`)
})

