# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Comment")

model.instance <- Comment$new()

test_that("prefix", {
  # tests for the property `prefix` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`prefix`, "EXPECTED_RESULT")
})

test_that("msg", {
  # tests for the property `msg` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`msg`, "EXPECTED_RESULT")
})

test_that("line_number", {
  # tests for the property `line_number` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`line_number`, "EXPECTED_RESULT")
})

