# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MzTab")

model.instance <- MzTab$new()

test_that("metadata", {
  # tests for the property `metadata` (Metadata)

  # uncomment below to test the property 
  #expect_equal(model.instance$`metadata`, "EXPECTED_RESULT")
})

test_that("smallMoleculeSummary", {
  # tests for the property `smallMoleculeSummary` (array[SmallMoleculeSummary])
  # The small molecule section is table-based. The small molecule section MUST always come after the metadata section. All table columns MUST be Tab separated. There MUST NOT be any empty cells; missing values MUST be reported using “null” for columns where Is Nullable &#x3D; “True”.  Each row of the small molecule section is intended to report one final result to be communicated in terms of a molecule that has been quantified. In many cases, this may be the molecule of biological interest, although in some cases, the final result could be a derivatized form as appropriate – although it is desirable for the database identifier(s) to reference to the biological (non-derivatized) form. In general, different adduct forms would generally be reported in the Small Molecule Feature section.  The order of columns MUST follow the order specified below.  All columns are MANDATORY except for “opt_” columns. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`smallMoleculeSummary`, "EXPECTED_RESULT")
})

test_that("smallMoleculeFeature", {
  # tests for the property `smallMoleculeFeature` (array[SmallMoleculeFeature])
  # The small molecule feature section is table-based, representing individual MS regions (generally considered to be the elution profile for all isotopomers formed from a single charge state of a molecule), that have been measured/quantified. However, for approaches that quantify individual isotopomers e.g. stable isotope labelling/flux studies, then each SMF row SHOULD represent a single isotopomer.  Different adducts or derivatives and different charge states of individual molecules should be reported as separate SMF rows.  The small molecule feature section MUST always come after the Small Molecule Table. All table columns MUST be Tab separated. There MUST NOT be any empty cells. Missing values MUST be reported using “null”.  The order of columns MUST follow the order specified below.  All columns are MANDATORY except for “opt_” columns. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`smallMoleculeFeature`, "EXPECTED_RESULT")
})

test_that("smallMoleculeEvidence", {
  # tests for the property `smallMoleculeEvidence` (array[SmallMoleculeEvidence])
  # The small molecule evidence section is table-based, representing evidence for identifications of small molecules/features, from database search or any other process used to give putative identifications to molecules. In a typical case, each row represents one result from a single search or intepretation of a piece of evidence e.g. a database search with a fragmentation spectrum. Multiple results from a given input data item (e.g. one fragment spectrum) SHOULD share the same value under evidence_input_id.  The small molecule evidence section MUST always come after the Small Molecule Feature Table. All table columns MUST be Tab separated. There MUST NOT be any empty cells. Missing values MUST be reported using “null”.  The order of columns MUST follow the order specified below.  All columns are MANDATORY except for “opt_” columns. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`smallMoleculeEvidence`, "EXPECTED_RESULT")
})

test_that("comment", {
  # tests for the property `comment` (array[Comment])
  # Comment lines can be placed anywhere in an mzTab file. These lines must start with the three-letter code COM and are ignored by most parsers. Empty lines can also occur anywhere in an mzTab file and are ignored. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`comment`, "EXPECTED_RESULT")
})

