# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ColumnParameterMapping")

model.instance <- ColumnParameterMapping$new()

test_that("column_name", {
  # tests for the property `column_name` (character)
  # The fully qualified target column name.

  # uncomment below to test the property 
  #expect_equal(model.instance$`column_name`, "EXPECTED_RESULT")
})

test_that("param", {
  # tests for the property `param` (Parameter)

  # uncomment below to test the property 
  #expect_equal(model.instance$`param`, "EXPECTED_RESULT")
})

