context("test-validate_json_api.R")

test_that("validation via REST API of mztab json works", {
  testfile <- system.file("testdata", c("lipidomics-example.mzTab.json"),package="rmzTabM")
  mzTabObject <- MzTab$new()
  mzTabObject$fromJSON(testfile)
  # the tests below currently fail, serialization produces empty publications list
  # expect_equal(1, mzTabObject$`metadata`$`publication`$id)
  # expect_equal("Publication", mzTabObject$`metadata`$`publication`$elementType)
  # expect_equal(2, length(mzTabObject$`metadata`$`publication`$publicationItems))
  # publications <- mzTabObject$`metadata`$`publication`$publicationItems
  # expect_equal("pubmed", publications[[1]]$type)
  # expect_equal("29039908", publications[[1]]$accesion)
  # expect_equal("doi", publications[[2]]$type)
  # expect_equal("10.1021/acs.analchem.7b03576", publications[[2]]$accesion)
  #expect_false(is.null(mzTabObject$toJSONString()))
  metadataJsonObject <- mzTabObject$`metadata`$toJSON()
  expect_false(is.null(metadataJsonObject))
  #cat(names(metadataJsonObject))
  expect_false(is.null(metadataJsonObject$`mzTab-version`))
  expect_false(is.null(metadataJsonObject$`mzTab-ID`))
  expect_equal("ISAS-2018-1234", metadataJsonObject$`mzTab-ID`)
  expect_false(is.null(metadataJsonObject$`description`))
  #metadataJsonObject$`title`
  expect_true(is.null(metadataJsonObject$`title`))
  expect_true(0 == length(metadataJsonObject$`title`))
  validateApi <- ValidateApi$new()
  browser()
  response <- validateApi$ValidateMzTabFile(mzTabObject, 'info', 50, FALSE)
  expect_false("API server error" == response$content)
  #browser()
  # the next test currently fails, there is an encoding error for description, which should be null in the json but is {}.
  expect_false("API client error" == response$content)
  
  expect_false(is.null(mzTabObject$metadata))
  # expect_false(is.null(mzTabObject$smallMoleculeSummary))
  # expect_false(is.null(mzTabObject$smallMoleculeFeature))
  # expect_false(is.null(mzTabObject$smallMoleculeEvidence))
  # expect_equal(object = mzTabObject$`metadata`$`mzTab-ID`, "ISAS-2018-1234")
  # expect_length(mzTabObject$`smallMoleculeSummary`,1)
  # expect_length(mzTabObject$`smallMoleculeEvidence`,4)
  # expect_length(mzTabObject$`smallMoleculeFeature`,4)
})
