# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OptColumnMapping")

model.instance <- OptColumnMapping$new()

test_that("identifier", {
  # tests for the property `identifier` (character)
  # The fully qualified column name.

  # uncomment below to test the property 
  #expect_equal(model.instance$`identifier`, "EXPECTED_RESULT")
})

test_that("param", {
  # tests for the property `param` (Parameter)

  # uncomment below to test the property 
  #expect_equal(model.instance$`param`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (character)
  # The value for this column in a particular row.

  # uncomment below to test the property 
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

