# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CVAllOf")

model.instance <- CVAllOf$new()

test_that("label", {
  # tests for the property `label` (character)
  # The abbreviated CV label.

  # uncomment below to test the property 
  #expect_equal(model.instance$`label`, "EXPECTED_RESULT")
})

test_that("full_name", {
  # tests for the property `full_name` (character)
  # The full name of this CV, for humans.

  # uncomment below to test the property 
  #expect_equal(model.instance$`full_name`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # The CV version used when the file was generated.

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("uri", {
  # tests for the property `uri` (character)
  # A URI to the CV definition.

  # uncomment below to test the property 
  #expect_equal(model.instance$`uri`, "EXPECTED_RESULT")
})

