# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PublicationItem")

test_that("toString", {
  model.instance <- PublicationItem$new()
  model.instance$`type` <- "pubmed"
  model.instance$`accession` <- "12897123"
  piString <- model.instance$toString()
  expect_equal(piString, "pubmed:12897123")
})

test_that("fromString", {
  model.instance <- PublicationItem$new()
  model.instance$fromString("pubmed:12897123")
  expect_equal(model.instance$`type`, "pubmed")
  expect_equal(model.instance$`accession`, "12897123")
})

