# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ValidationMessage")

model.instance <- ValidationMessage$new()

test_that("code", {
  # tests for the property `code` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

test_that("category", {
  # tests for the property `category` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`category`, "EXPECTED_RESULT")
})

test_that("message_type", {
  # tests for the property `message_type` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`message_type`, "EXPECTED_RESULT")
})

test_that("message", {
  # tests for the property `message` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

test_that("line_number", {
  # tests for the property `line_number` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`line_number`, "EXPECTED_RESULT")
})

