# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test IndexedElement")

model.instance <- IndexedElement$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("elementType", {
  # tests for the property `elementType` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`elementType`, "EXPECTED_RESULT")
})

