# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@isas.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AssayAllOf
#' @description AssayAllOf Class
#' @format An \code{R6Class} generator object
#' @field name  character 
#'
#' @field custom  list( \link{Parameter} ) [optional]
#'
#' @field external_uri  character [optional]
#'
#' @field sample_ref  \link{Sample} [optional]
#'
#' @field ms_run_ref  list( \link{MsRun} ) 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AssayAllOf <- R6::R6Class(
  'AssayAllOf',
  public = list(
    `name` = NULL,
    `custom` = NULL,
    `external_uri` = NULL,
    `sample_ref` = NULL,
    `ms_run_ref` = NULL,
    initialize = function(`name`, `ms_run_ref`, `custom`=NULL, `external_uri`=NULL, `sample_ref`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`ms_run_ref`)) {
        stopifnot(is.vector(`ms_run_ref`), length(`ms_run_ref`) != 0)
        sapply(`ms_run_ref`, function(x) stopifnot(R6::is.R6(x)))
        self$`ms_run_ref` <- `ms_run_ref`
      }
      if (!is.null(`custom`)) {
        stopifnot(is.vector(`custom`), length(`custom`) != 0)
        sapply(`custom`, function(x) stopifnot(R6::is.R6(x)))
        self$`custom` <- `custom`
      }
      if (!is.null(`external_uri`)) {
        stopifnot(is.character(`external_uri`), length(`external_uri`) == 1)
        self$`external_uri` <- `external_uri`
      }
      if (!is.null(`sample_ref`)) {
        stopifnot(R6::is.R6(`sample_ref`))
        self$`sample_ref` <- `sample_ref`
      }
    },
    toJSON = function() {
      AssayAllOfObject <- list()
      if (!is.null(self$`name`)) {
        AssayAllOfObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`custom`)) {
        AssayAllOfObject[['custom']] <-
          lapply(self$`custom`, function(x) x$toJSON())
      }
      if (!is.null(self$`external_uri`)) {
        AssayAllOfObject[['external_uri']] <-
          self$`external_uri`
      }
      if (!is.null(self$`sample_ref`)) {
        AssayAllOfObject[['sample_ref']] <-
          self$`sample_ref`$toJSON()
      }
      if (!is.null(self$`ms_run_ref`)) {
        AssayAllOfObject[['ms_run_ref']] <-
          lapply(self$`ms_run_ref`, function(x) x$toJSON())
      }

      AssayAllOfObject
    },
    fromJSON = function(AssayAllOfJson) {
      AssayAllOfObject <- jsonlite::fromJSON(AssayAllOfJson)
      if (!is.null(AssayAllOfObject$`name`)) {
        self$`name` <- AssayAllOfObject$`name`
      }
      if (!is.null(AssayAllOfObject$`custom`)) {
        self$`custom` <- ApiClient$new()$deserializeObj(AssayAllOfObject$`custom`, "array[Parameter]", loadNamespace("rmzTabM"))
      }
      if (!is.null(AssayAllOfObject$`external_uri`)) {
        self$`external_uri` <- AssayAllOfObject$`external_uri`
      }
      if (!is.null(AssayAllOfObject$`sample_ref`)) {
        sample_refObject <- Sample$new()
        sample_refObject$fromJSON(jsonlite::toJSON(AssayAllOfObject$sample_ref, auto_unbox = TRUE, digits = NA))
        self$`sample_ref` <- sample_refObject
      }
      if (!is.null(AssayAllOfObject$`ms_run_ref`)) {
        self$`ms_run_ref` <- ApiClient$new()$deserializeObj(AssayAllOfObject$`ms_run_ref`, "array[MsRun]", loadNamespace("rmzTabM"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`custom`)) {
        sprintf(
        '"custom":
        [%s]
',
        paste(sapply(self$`custom`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`external_uri`)) {
        sprintf(
        '"external_uri":
          "%s"
                ',
        self$`external_uri`
        )},
        if (!is.null(self$`sample_ref`)) {
        sprintf(
        '"sample_ref":
        %s
        ',
        jsonlite::toJSON(self$`sample_ref`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`ms_run_ref`)) {
        sprintf(
        '"ms_run_ref":
        [%s]
',
        paste(sapply(self$`ms_run_ref`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AssayAllOfJson) {
      AssayAllOfObject <- jsonlite::fromJSON(AssayAllOfJson)
      self$`name` <- AssayAllOfObject$`name`
      self$`custom` <- ApiClient$new()$deserializeObj(AssayAllOfObject$`custom`, "array[Parameter]", loadNamespace("rmzTabM"))
      self$`external_uri` <- AssayAllOfObject$`external_uri`
      self$`sample_ref` <- Sample$new()$fromJSON(jsonlite::toJSON(AssayAllOfObject$sample_ref, auto_unbox = TRUE, digits = NA))
      self$`ms_run_ref` <- ApiClient$new()$deserializeObj(AssayAllOfObject$`ms_run_ref`, "array[MsRun]", loadNamespace("rmzTabM"))
      self
    }
  )
)
