# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@cebitec.uni-bielefeld.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ColumnParameterMapping
#' @description ColumnParameterMapping Class
#' @format An \code{R6Class} generator object
#' @field column_name  character 
#'
#' @field param  \link{Parameter} 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ColumnParameterMapping <- R6::R6Class(
  'ColumnParameterMapping',
  public = list(
    `column_name` = NULL,
    `param` = NULL,
    initialize = function(`column_name`, `param`, ...){
      local.optional.var <- list(...)
      if (!missing(`column_name`)) {
        stopifnot(is.character(`column_name`), length(`column_name`) == 1)
        self$`column_name` <- `column_name`
      }
      if (!missing(`param`)) {
        stopifnot(R6::is.R6(`param`))
        self$`param` <- `param`
      }
    },
    toJSON = function() {
      ColumnParameterMappingObject <- list()
      if (!is.null(self$`column_name`)) {
        ColumnParameterMappingObject[['column_name']] <-
          rmzTabM::safe_unbox(self$`column_name`)
      }
      if (!is.null(self$`param`)) {
        ColumnParameterMappingObject[['param']] <-
          self$`param`$toJSON()
      }

      ColumnParameterMappingObject
    },
    fromJSON = function(ColumnParameterMappingJson) {
      ColumnParameterMappingObject <- jsonlite::fromJSON(ColumnParameterMappingJson)
      if (!is.null(ColumnParameterMappingObject$`column_name`)) {
        self$`column_name` <- ColumnParameterMappingObject$`column_name`
      }
      if (!is.null(ColumnParameterMappingObject$`param`)) {
        paramObject <- Parameter$new()
        paramObject$fromJSON(jsonlite::toJSON(ColumnParameterMappingObject$param, auto_unbox = TRUE, null = "null", na = "null", digits = NA))
        self$`param` <- paramObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`column_name`)) {
        sprintf(
        '"column_name":
          "%s"
                ',
        rmzTabM::safe_unbox(self$`column_name`)
        )},
        if (!is.null(self$`param`)) {
        sprintf(
        '"param":
        %s
        ',
        jsonlite::toJSON(self$`param`$toJSON(), auto_unbox=FALSE, null = "null", na = "null", digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ColumnParameterMappingJson) {
      ColumnParameterMappingObject <- jsonlite::fromJSON(ColumnParameterMappingJson)
      self$`column_name` <- ColumnParameterMappingObject$`column_name`
      self$`param` <- Parameter$new()$fromJSONString(jsonlite::toJSON(ColumnParameterMappingObject$param, auto_unbox = TRUE, null = "null", na = "null", digits = NA))
      self
    },
    # type can be small_molecule, small_molecule_feature or small_molecule_evidence
    toDataFrame = function(type="small_molecule") {
      elements <- data.frame(PREFIX=character(), KEY=character(), VALUE=character())
      if (!is.null(self$`column_name`) && !is.null(self$`param`)) {
        elements <-
          rbind(elements,
                list(
                  PREFIX = "MTD",
                  KEY = paste("colunit", type, sep="-"),
                  VALUE = paste(self$`column_name`, self$`param`$toString(), sep = "=")
                ),
                stringsAsFactors = FALSE)
      }
      elements
    },
    fromDataFrame = function(ColumnParameterMappingDataFrame) {
      # TODO
      warning("fromDataFrame not implemented yet")
    }
  )
)
