# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@isas.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Contact
#' @description Contact Class
#' @format An \code{R6Class} generator object
#' @field id  integer [optional]
#'
#' @field name  character [optional]
#'
#' @field affiliation  character [optional]
#'
#' @field email  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Contact <- R6::R6Class(
  'Contact',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `affiliation` = NULL,
    `email` = NULL,
    initialize = function(`id`=NULL, `name`=NULL, `affiliation`=NULL, `email`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`affiliation`)) {
        stopifnot(is.character(`affiliation`), length(`affiliation`) == 1)
        self$`affiliation` <- `affiliation`
      }
      if (!is.null(`email`)) {
        stopifnot(is.character(`email`), length(`email`) == 1)
        self$`email` <- `email`
      }
    },
    toJSON = function() {
      ContactObject <- list()
      if (!is.null(self$`id`)) {
        ContactObject[['id']] <-
          rmzTabM::safe_unbox(self$`id`)
      }
      if (!is.null(self$`name`)) {
        ContactObject[['name']] <-
          rmzTabM::safe_unbox(self$`name`)
      }
      if (!is.null(self$`affiliation`)) {
        ContactObject[['affiliation']] <-
          rmzTabM::safe_unbox(self$`affiliation`)
      }
      if (!is.null(self$`email`)) {
        ContactObject[['email']] <-
          rmzTabM::safe_unbox(self$`email`)
      }

      ContactObject
    },
    fromJSON = function(ContactJson) {
      ContactObject <- jsonlite::fromJSON(ContactJson)
      if (!is.null(ContactObject$`id`)) {
        self$`id` <- ContactObject$`id`
      }
      if (!is.null(ContactObject$`name`)) {
        self$`name` <- ContactObject$`name`
      }
      if (!is.null(ContactObject$`affiliation`)) {
        self$`affiliation` <- ContactObject$`affiliation`
      }
      if (!is.null(ContactObject$`email`)) {
        self$`email` <- ContactObject$`email`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        rmzTabM::safe_unbox(self$`id`)
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        rmzTabM::safe_unbox(self$`name`)
        )},
        if (!is.null(self$`affiliation`)) {
        sprintf(
        '"affiliation":
          "%s"
                ',
        rmzTabM::safe_unbox(self$`affiliation`)
        )},
        if (!is.null(self$`email`)) {
        sprintf(
        '"email":
          "%s"
                ',
        rmzTabM::safe_unbox(self$`email`)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ContactJson) {
      ContactObject <- jsonlite::fromJSON(ContactJson)
      self$`id` <- ContactObject$`id`
      self$`name` <- ContactObject$`name`
      self$`affiliation` <- ContactObject$`affiliation`
      self$`email` <- ContactObject$`email`
      self
    },
    toDataFrame = function() {
      idPrefix <- paste0("contact[", self$`id`, "]")
      elements <- data.frame(PREFIX=character(), KEY=character(), VALUE=character())
      if (!is.null(self$`name`)) {
        name <- list(
          PREFIX = "MTD",
          KEY = paste(idPrefix, "name", sep = "-"),
          VALUE = self$`name`
        )
        elements <-
          rbind(elements,
                name,
                stringsAsFactors = FALSE)
      }
      if (!is.null(self$`affiliation`)) {
        affiliation <- list(
          PREFIX = "MTD",
          KEY = paste(idPrefix, "affiliation", sep = "-"),
          VALUE = self$`affiliation`
        )
        elements <-
          rbind(elements,
                affiliation,
                stringsAsFactors = FALSE)
      }
      if (!is.null(self$`email`)) {
        email <- list(
          PREFIX = "MTD",
          KEY = paste(idPrefix, "email", sep = "-"),
          VALUE = self$`email`
        )
        elements <-
          rbind(elements,
                email,
                stringsAsFactors = FALSE)
      }
      elements
    }
  )
)
