# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@isas.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CVAllOf
#' @description CVAllOf Class
#' @format An \code{R6Class} generator object
#' @field label  character 
#'
#' @field full_name  character 
#'
#' @field version  character 
#'
#' @field uri  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CVAllOf <- R6::R6Class(
  'CVAllOf',
  public = list(
    `label` = NULL,
    `full_name` = NULL,
    `version` = NULL,
    `uri` = NULL,
    initialize = function(`label`, `full_name`, `version`, `uri`, ...){
      local.optional.var <- list(...)
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`full_name`)) {
        stopifnot(is.character(`full_name`), length(`full_name`) == 1)
        self$`full_name` <- `full_name`
      }
      if (!missing(`version`)) {
        stopifnot(is.character(`version`), length(`version`) == 1)
        self$`version` <- `version`
      }
      if (!missing(`uri`)) {
        stopifnot(is.character(`uri`), length(`uri`) == 1)
        self$`uri` <- `uri`
      }
    },
    toJSON = function() {
      CVAllOfObject <- list()
      if (!is.null(self$`label`)) {
        CVAllOfObject[['label']] <-
          self$`label`
      }
      if (!is.null(self$`full_name`)) {
        CVAllOfObject[['full_name']] <-
          self$`full_name`
      }
      if (!is.null(self$`version`)) {
        CVAllOfObject[['version']] <-
          self$`version`
      }
      if (!is.null(self$`uri`)) {
        CVAllOfObject[['uri']] <-
          self$`uri`
      }

      CVAllOfObject
    },
    fromJSON = function(CVAllOfJson) {
      CVAllOfObject <- jsonlite::fromJSON(CVAllOfJson)
      if (!is.null(CVAllOfObject$`label`)) {
        self$`label` <- CVAllOfObject$`label`
      }
      if (!is.null(CVAllOfObject$`full_name`)) {
        self$`full_name` <- CVAllOfObject$`full_name`
      }
      if (!is.null(CVAllOfObject$`version`)) {
        self$`version` <- CVAllOfObject$`version`
      }
      if (!is.null(CVAllOfObject$`uri`)) {
        self$`uri` <- CVAllOfObject$`uri`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`label`)) {
        sprintf(
        '"label":
          "%s"
                ',
        self$`label`
        )},
        if (!is.null(self$`full_name`)) {
        sprintf(
        '"full_name":
          "%s"
                ',
        self$`full_name`
        )},
        if (!is.null(self$`version`)) {
        sprintf(
        '"version":
          "%s"
                ',
        self$`version`
        )},
        if (!is.null(self$`uri`)) {
        sprintf(
        '"uri":
          "%s"
                ',
        self$`uri`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CVAllOfJson) {
      CVAllOfObject <- jsonlite::fromJSON(CVAllOfJson)
      self$`label` <- CVAllOfObject$`label`
      self$`full_name` <- CVAllOfObject$`full_name`
      self$`version` <- CVAllOfObject$`version`
      self$`uri` <- CVAllOfObject$`uri`
      self
    }
  )
)
