# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@cebitec.uni-bielefeld.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Database
#' @description Database Class
#' @format An \code{R6Class} generator object
#' @field id  integer [optional]
#'
#' @field param  \link{Parameter} 
#'
#' @field prefix  character 
#'
#' @field version  character 
#'
#' @field uri  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Database <- R6::R6Class(
  'Database',
  public = list(
    `id` = NULL,
    `param` = NULL,
    `prefix` = NULL,
    `version` = NULL,
    `uri` = NULL,
    initialize = function(`param`, `prefix`, `version`, `uri`, `id`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`param`)) {
        stopifnot(R6::is.R6(`param`))
        self$`param` <- `param`
      }
      if (!missing(`prefix`)) {
        stopifnot(is.character(`prefix`), length(`prefix`) == 1)
        self$`prefix` <- `prefix`
      }
      if (!missing(`version`)) {
        stopifnot(is.character(`version`), length(`version`) == 1)
        self$`version` <- `version`
      }
      if (!missing(`uri`)) {
        stopifnot(is.character(`uri`), length(`uri`) == 1)
        self$`uri` <- `uri`
      }
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
    },
    toJSON = function() {
      DatabaseObject <- list()
      if (!is.null(self$`id`)) {
        DatabaseObject[['id']] <-
          rmzTabM::safe_unbox(self$`id`)
      }
      if (!is.null(self$`param`)) {
        DatabaseObject[['param']] <-
          self$`param`$toJSON()
      }
      if (!is.null(self$`prefix`)) {
        DatabaseObject[['prefix']] <-
          rmzTabM::safe_unbox(self$`prefix`)
      }
      if (!is.null(self$`version`)) {
        DatabaseObject[['version']] <-
          rmzTabM::safe_unbox(self$`version`)
      }
      if (!is.null(self$`uri`)) {
        DatabaseObject[['uri']] <-
          rmzTabM::safe_unbox(self$`uri`)
      }

      DatabaseObject
    },
    fromJSON = function(DatabaseJson) {
      DatabaseObject <- jsonlite::fromJSON(DatabaseJson)
      if (!is.null(DatabaseObject$`id`)) {
        self$`id` <- DatabaseObject$`id`
      }
      if (!is.null(DatabaseObject$`param`)) {
        paramObject <- Parameter$new()
        paramObject$fromJSON(jsonlite::toJSON(DatabaseObject$param, auto_unbox = TRUE, null = "null", na = "null", digits = NA))
        self$`param` <- paramObject
      }
      if (!is.null(DatabaseObject$`prefix`)) {
        self$`prefix` <- DatabaseObject$`prefix`
      }
      if (!is.null(DatabaseObject$`version`)) {
        self$`version` <- DatabaseObject$`version`
      }
      if (!is.null(DatabaseObject$`uri`)) {
        self$`uri` <- DatabaseObject$`uri`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        rmzTabM::safe_unbox(self$`id`)
        )},
        if (!is.null(self$`param`)) {
        sprintf(
        '"param":
        %s
        ',
        jsonlite::toJSON(self$`param`$toJSON(), auto_unbox=FALSE, null = "null", na = "null", digits = NA)
        )},
        if (!is.null(self$`prefix`)) {
        sprintf(
        '"prefix":
          "%s"
                ',
        rmzTabM::safe_unbox(self$`prefix`)
        )},
        if (!is.null(self$`version`)) {
        sprintf(
        '"version":
          "%s"
                ',
        rmzTabM::safe_unbox(self$`version`)
        )},
        if (!is.null(self$`uri`)) {
        sprintf(
        '"uri":
          "%s"
                ',
        rmzTabM::safe_unbox(self$`uri`)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DatabaseJson) {
      DatabaseObject <- jsonlite::fromJSON(DatabaseJson)
      self$`id` <- DatabaseObject$`id`
      self$`param` <- Parameter$new()$fromJSONString(jsonlite::toJSON(DatabaseObject$param, auto_unbox = TRUE, null = "null", na = "null", digits = NA))
      self$`prefix` <- DatabaseObject$`prefix`
      self$`version` <- DatabaseObject$`version`
      self$`uri` <- DatabaseObject$`uri`
      self
    },
    toDataFrame = function() {
      idPrefix <- paste0("database[", self$`id`, "]")
      elements <- data.frame(PREFIX=character(), KEY=character(), VALUE=character())
      if (!is.null(self$`param`)) {
        elements <-
          rbind(elements,
                list(
                  PREFIX = "MTD",
                  KEY = idPrefix,
                  VALUE = self$`param`$toString()
                ),
                stringsAsFactors = FALSE)
      }
      if (!is.null(self$`prefix`)) {
        elements <-
          rbind(elements,
                list(
                  PREFIX = "MTD",
                  KEY = paste(idPrefix, "prefix", sep = "-"),
                  VALUE = self$`prefix`
                ),
                stringsAsFactors = FALSE)
      }
      if (!is.null(self$`version`)) {
        elements <-
          rbind(elements,
                list(
                  PREFIX = "MTD",
                  KEY = paste(idPrefix, "version", sep = "-"),
                  VALUE = self$`version`
                ),
                stringsAsFactors = FALSE)
      }
      if (!is.null(self$`uri`)) {
        elements <-
          rbind(elements,
                list(
                  PREFIX = "MTD",
                  KEY = paste(idPrefix, "uri", sep = "-"),
                  VALUE = self$`uri`
                ),
                stringsAsFactors = FALSE)
      }
      elements
    },
    fromDataFrame = function(DatabaseDataFrame) {
      stopifnot(nrow(DatabaseDataFrame)==1)
      if (rlang::has_name(DatabaseDataFrame, "id")) {
        self$`id` <- as.numeric(DatabaseDataFrame$`id`)
      }
      if (rlang::has_name(DatabaseDataFrame, "param")) {
        param <- Parameter$new()
        param$fromString(NULL, DatabaseDataFrame$`param`)
        self$`param` <- param
      }
      if (rlang::has_name(DatabaseDataFrame, "prefix")) {
        self$`prefix` <- DatabaseDataFrame$`prefix`
      }
      if (rlang::has_name(DatabaseDataFrame, "version")) {
        self$`version` <- DatabaseDataFrame$`version`
      }
      if (rlang::has_name(DatabaseDataFrame, "uri")) {
        self$`uri` <- DatabaseDataFrame$`uri`
      }
      self
    }
  )
)
