# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@isas.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title IndexedElement
#' @description IndexedElement Class
#' @format An \code{R6Class} generator object
#' @field id  integer 
#'
#' @field elementType  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
IndexedElement <- R6::R6Class(
  'IndexedElement',
  public = list(
    `id` = NULL,
    `elementType` = NULL,
    initialize = function(`id`, `elementType`, ...){
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`elementType`)) {
        stopifnot(is.character(`elementType`), length(`elementType`) == 1)
        self$`elementType` <- `elementType`
      }
    },
    toJSON = function() {
      IndexedElementObject <- list()
      if (!is.null(self$`id`)) {
        IndexedElementObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`elementType`)) {
        IndexedElementObject[['elementType']] <-
          self$`elementType`
      }

      IndexedElementObject
    },
    fromJSON = function(IndexedElementJson) {
      IndexedElementObject <- jsonlite::fromJSON(IndexedElementJson)
      if (!is.null(IndexedElementObject$`id`)) {
        self$`id` <- IndexedElementObject$`id`
      }
      if (!is.null(IndexedElementObject$`elementType`)) {
        self$`elementType` <- IndexedElementObject$`elementType`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`elementType`)) {
        sprintf(
        '"elementType":
          "%s"
                ',
        self$`elementType`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(IndexedElementJson) {
      IndexedElementObject <- jsonlite::fromJSON(IndexedElementJson)
      self$`id` <- IndexedElementObject$`id`
      self$`elementType` <- IndexedElementObject$`elementType`
      self
    }
  )
)
