# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@isas.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Instrument
#' @description Instrument Class
#' @format An \code{R6Class} generator object
#' @field id  integer 
#'
#' @field elementType  character 
#'
#' @field name  \link{Parameter} [optional]
#'
#' @field source  \link{Parameter} [optional]
#'
#' @field analyzer  list( \link{Parameter} ) [optional]
#'
#' @field detector  \link{Parameter} [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Instrument <- R6::R6Class(
  'Instrument',
  public = list(
    `id` = NULL,
    `elementType` = NULL,
    `name` = NULL,
    `source` = NULL,
    `analyzer` = NULL,
    `detector` = NULL,
    initialize = function(`id`, `elementType`, `name`=NULL, `source`=NULL, `analyzer`=NULL, `detector`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`elementType`)) {
        stopifnot(is.character(`elementType`), length(`elementType`) == 1)
        self$`elementType` <- `elementType`
      }
      if (!is.null(`name`)) {
        stopifnot(R6::is.R6(`name`))
        self$`name` <- `name`
      }
      if (!is.null(`source`)) {
        stopifnot(R6::is.R6(`source`))
        self$`source` <- `source`
      }
      if (!is.null(`analyzer`)) {
        stopifnot(is.vector(`analyzer`), length(`analyzer`) != 0)
        sapply(`analyzer`, function(x) stopifnot(R6::is.R6(x)))
        self$`analyzer` <- `analyzer`
      }
      if (!is.null(`detector`)) {
        stopifnot(R6::is.R6(`detector`))
        self$`detector` <- `detector`
      }
    },
    toJSON = function() {
      InstrumentObject <- list()
      if (!is.null(self$`id`)) {
        InstrumentObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`elementType`)) {
        InstrumentObject[['elementType']] <-
          self$`elementType`
      }
      if (!is.null(self$`name`)) {
        InstrumentObject[['name']] <-
          self$`name`$toJSON()
      }
      if (!is.null(self$`source`)) {
        InstrumentObject[['source']] <-
          self$`source`$toJSON()
      }
      if (!is.null(self$`analyzer`)) {
        InstrumentObject[['analyzer']] <-
          lapply(self$`analyzer`, function(x) x$toJSON())
      }
      if (!is.null(self$`detector`)) {
        InstrumentObject[['detector']] <-
          self$`detector`$toJSON()
      }

      InstrumentObject
    },
    fromJSON = function(InstrumentJson) {
      InstrumentObject <- jsonlite::fromJSON(InstrumentJson)
      if (!is.null(InstrumentObject$`id`)) {
        self$`id` <- InstrumentObject$`id`
      }
      if (!is.null(InstrumentObject$`elementType`)) {
        self$`elementType` <- InstrumentObject$`elementType`
      }
      if (!is.null(InstrumentObject$`name`)) {
        nameObject <- Parameter$new()
        nameObject$fromJSON(jsonlite::toJSON(InstrumentObject$name, auto_unbox = TRUE, digits = NA))
        self$`name` <- nameObject
      }
      if (!is.null(InstrumentObject$`source`)) {
        sourceObject <- Parameter$new()
        sourceObject$fromJSON(jsonlite::toJSON(InstrumentObject$source, auto_unbox = TRUE, digits = NA))
        self$`source` <- sourceObject
      }
      if (!is.null(InstrumentObject$`analyzer`)) {
        self$`analyzer` <- ApiClient$new()$deserializeObj(InstrumentObject$`analyzer`, "array[Parameter]", loadNamespace("rmzTabM"))
      }
      if (!is.null(InstrumentObject$`detector`)) {
        detectorObject <- Parameter$new()
        detectorObject$fromJSON(jsonlite::toJSON(InstrumentObject$detector, auto_unbox = TRUE, digits = NA))
        self$`detector` <- detectorObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`elementType`)) {
        sprintf(
        '"elementType":
          "%s"
                ',
        self$`elementType`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
        %s
        ',
        jsonlite::toJSON(self$`name`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`source`)) {
        sprintf(
        '"source":
        %s
        ',
        jsonlite::toJSON(self$`source`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`analyzer`)) {
        sprintf(
        '"analyzer":
        [%s]
',
        paste(sapply(self$`analyzer`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`detector`)) {
        sprintf(
        '"detector":
        %s
        ',
        jsonlite::toJSON(self$`detector`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InstrumentJson) {
      InstrumentObject <- jsonlite::fromJSON(InstrumentJson)
      self$`id` <- InstrumentObject$`id`
      self$`elementType` <- InstrumentObject$`elementType`
      self$`name` <- Parameter$new()$fromJSON(jsonlite::toJSON(InstrumentObject$name, auto_unbox = TRUE, digits = NA))
      self$`source` <- Parameter$new()$fromJSON(jsonlite::toJSON(InstrumentObject$source, auto_unbox = TRUE, digits = NA))
      self$`analyzer` <- ApiClient$new()$deserializeObj(InstrumentObject$`analyzer`, "array[Parameter]", loadNamespace("rmzTabM"))
      self$`detector` <- Parameter$new()$fromJSON(jsonlite::toJSON(InstrumentObject$detector, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
