# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@isas.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MsRun
#' @description MsRun Class
#' @format An \code{R6Class} generator object
#' @field id  integer 
#'
#' @field name  character 
#'
#' @field location  character 
#'
#' @field instrument_ref  \link{Instrument} [optional]
#'
#' @field format  \link{Parameter} [optional]
#'
#' @field id_format  \link{Parameter} [optional]
#'
#' @field fragmentation_method  list( \link{Parameter} ) [optional]
#'
#' @field scan_polarity  list( \link{Parameter} ) [optional]
#'
#' @field hash  character [optional]
#'
#' @field hash_method  \link{Parameter} [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MsRun <- R6::R6Class(
  'MsRun',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `location` = NULL,
    `instrument_ref` = NULL,
    `format` = NULL,
    `id_format` = NULL,
    `fragmentation_method` = NULL,
    `scan_polarity` = NULL,
    `hash` = NULL,
    `hash_method` = NULL,
    initialize = function(`id`, `name`, `location`, `instrument_ref`=NULL, `format`=NULL, `id_format`=NULL, `fragmentation_method`=NULL, `scan_polarity`=NULL, `hash`=NULL, `hash_method`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`location`)) {
        stopifnot(is.character(`location`), length(`location`) == 1)
        self$`location` <- `location`
      }
      if (!is.null(`instrument_ref`)) {
        stopifnot(is.vector(`instrument_ref`), length(`instrument_ref`) != 0)
        sapply(`instrument_ref`, function(x) stopifnot(is.character(x)))
        self$`instrument_ref` <- `instrument_ref`
      }
      if (!is.null(`format`)) {
        stopifnot(R6::is.R6(`format`))
        self$`format` <- `format`
      }
      if (!is.null(`id_format`)) {
        stopifnot(R6::is.R6(`id_format`))
        self$`id_format` <- `id_format`
      }
      if (!is.null(`fragmentation_method`)) {
        stopifnot(is.vector(`fragmentation_method`), length(`fragmentation_method`) != 0)
        sapply(`fragmentation_method`, function(x) stopifnot(R6::is.R6(x)))
        self$`fragmentation_method` <- `fragmentation_method`
      }
      if (!is.null(`scan_polarity`)) {
        stopifnot(is.vector(`scan_polarity`), length(`scan_polarity`) != 0)
        sapply(`scan_polarity`, function(x) stopifnot(R6::is.R6(x)))
        self$`scan_polarity` <- `scan_polarity`
      }
      if (!is.null(`hash`)) {
        stopifnot(is.character(`hash`), length(`hash`) == 1)
        self$`hash` <- `hash`
      }
      if (!is.null(`hash_method`)) {
        stopifnot(R6::is.R6(`hash_method`))
        self$`hash_method` <- `hash_method`
      }
    },
    toJSON = function() {
      MsRunObject <- list()
      if (!is.null(self$`id`)) {
        MsRunObject[['id']] <-
          jsonlite::unbox(self$`id`)
      }
      if (!is.null(self$`name`)) {
        MsRunObject[['name']] <-
          jsonlite::unbox(self$`name`)
      }
      if (!is.null(self$`location`)) {
        MsRunObject[['location']] <-
          jsonlite::unbox(self$`location`)
      }
      if (!is.null(self$`instrument_ref`)) {
        MsRunObject[['instrument_ref']] <-
          self$`instrument_ref`
      }
      if (!is.null(self$`format`)) {
        MsRunObject[['format']] <-
          self$`format`$toJSON()
      }
      if (!is.null(self$`id_format`)) {
        MsRunObject[['id_format']] <-
          self$`id_format`$toJSON()
      }
      if (!is.null(self$`fragmentation_method`)) {
        MsRunObject[['fragmentation_method']] <-
          lapply(self$`fragmentation_method`, function(x) x$toJSON())
      }
      if (!is.null(self$`scan_polarity`)) {
        MsRunObject[['scan_polarity']] <-
          lapply(self$`scan_polarity`, function(x) x$toJSON())
      }
      if (!is.null(self$`hash`)) {
        MsRunObject[['hash']] <-
          jsonlite::unbox(self$`hash`)
      }
      if (!is.null(self$`hash_method`)) {
        MsRunObject[['hash_method']] <-
          self$`hash_method`$toJSON()
      }

      MsRunObject
    },
    fromJSON = function(MsRunJson) {
      MsRunObject <- jsonlite::fromJSON(MsRunJson)
      if (!is.null(MsRunObject$`id`)) {
        self$`id` <- MsRunObject$`id`
      }
      if (!is.null(MsRunObject$`name`)) {
        self$`name` <- MsRunObject$`name`
      }
      if (!is.null(MsRunObject$`location`)) {
        self$`location` <- MsRunObject$`location`
      }
      if (!is.null(MsRunObject$`instrument_ref`)) {
        self$`instrument_ref` <- ApiClient$new()$deserializeObj(MsRunObject$`instrument_ref`, "array[integer]", loadNamespace("rmzTabM"))
      }
      if (!is.null(MsRunObject$`format`)) {
        formatObject <- Parameter$new()
        formatObject$fromJSON(jsonlite::toJSON(MsRunObject$format, auto_unbox = TRUE, null = "null", na = "null", digits = NA))
        self$`format` <- formatObject
      }
      if (!is.null(MsRunObject$`id_format`)) {
        id_formatObject <- Parameter$new()
        id_formatObject$fromJSON(jsonlite::toJSON(MsRunObject$id_format, auto_unbox = TRUE, null = "null", na = "null", digits = NA))
        self$`id_format` <- id_formatObject
      }
      if (!is.null(MsRunObject$`fragmentation_method`)) {
        self$`fragmentation_method` <- ApiClient$new()$deserializeObj(MsRunObject$`fragmentation_method`, "array[Parameter]", loadNamespace("rmzTabM"))
      }
      if (!is.null(MsRunObject$`scan_polarity`)) {
        self$`scan_polarity` <- ApiClient$new()$deserializeObj(MsRunObject$`scan_polarity`, "array[Parameter]", loadNamespace("rmzTabM"))
      }
      if (!is.null(MsRunObject$`hash`)) {
        self$`hash` <- MsRunObject$`hash`
      }
      if (!is.null(MsRunObject$`hash_method`)) {
        hash_methodObject <- Parameter$new()
        hash_methodObject$fromJSON(jsonlite::toJSON(MsRunObject$hash_method, auto_unbox = TRUE, null = "null", na = "null", digits = NA))
        self$`hash_method` <- hash_methodObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        jsonlite::unbox(self$`id`)
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        jsonlite::unbox(self$`name`)
        )},
        if (!is.null(self$`location`)) {
        sprintf(
        '"location":
          "%s"
                ',
        jsonlite::unbox(self$`location`)
        )},
        if (!is.null(self$`instrument_ref`)) {
        sprintf(
        '"instrument_ref":
        [%s]
        ',
        paste(unlist(lapply(self$`ms_run_ref`, function(x) paste0(x))), collapse=",")
        )},
        if (!is.null(self$`format`)) {
        sprintf(
        '"format":
        %s
        ',
        jsonlite::toJSON(self$`format`$toJSON(), auto_unbox=FALSE, null = "null", na = "null", digits = NA)
        )},
        if (!is.null(self$`id_format`)) {
        sprintf(
        '"id_format":
        %s
        ',
        jsonlite::toJSON(self$`id_format`$toJSON(), auto_unbox=FALSE, null = "null", na = "null", digits = NA)
        )},
        if (!is.null(self$`fragmentation_method`)) {
        sprintf(
        '"fragmentation_method":
        %s
',
        paste(sapply(self$`fragmentation_method`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=FALSE, null = "null", na = "null", digits = NA)), collapse=",")
        )},
        if (!is.null(self$`scan_polarity`)) {
        sprintf(
        '"scan_polarity":
        %s
',
        paste(sapply(self$`scan_polarity`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=FALSE, null = "null", na = "null", digits = NA)), collapse=",")
        )},
        if (!is.null(self$`hash`)) {
        sprintf(
        '"hash":
          "%s"
                ',
        jsonlite::unbox(self$`hash`)
        )},
        if (!is.null(self$`hash_method`)) {
        sprintf(
        '"hash_method":
        %s
        ',
        jsonlite::toJSON(self$`hash_method`$toJSON(), auto_unbox=FALSE, null = "null", na = "null", digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MsRunJson) {
      MsRunObject <- jsonlite::fromJSON(MsRunJson)
      self$`id` <- MsRunObject$`id`
      self$`name` <- MsRunObject$`name`
      self$`location` <- MsRunObject$`location`
      self$`instrument_ref` <- Instrument$new()$fromJSONString(jsonlite::toJSON(MsRunObject$instrument_ref, auto_unbox = TRUE, null = "null", na = "null", digits = NA))
      self$`format` <- Parameter$new()$fromJSONString(jsonlite::toJSON(MsRunObject$format, auto_unbox = TRUE, null = "null", na = "null", digits = NA))
      self$`id_format` <- Parameter$new()$fromJSONString(jsonlite::toJSON(MsRunObject$id_format, auto_unbox = TRUE, null = "null", na = "null", digits = NA))
      self$`fragmentation_method` <- ApiClient$new()$deserializeObj(MsRunObject$`fragmentation_method`, "array[Parameter]", loadNamespace("rmzTabM"))
      self$`scan_polarity` <- ApiClient$new()$deserializeObj(MsRunObject$`scan_polarity`, "array[Parameter]", loadNamespace("rmzTabM"))
      self$`hash` <- MsRunObject$`hash`
      self$`hash_method` <- Parameter$new()$fromJSONString(jsonlite::toJSON(MsRunObject$hash_method, auto_unbox = TRUE, null = "null", na = "null", digits = NA))
      self
    }
  )
)
