# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@isas.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title OptColumnMapping
#' @description OptColumnMapping Class
#' @format An \code{R6Class} generator object
#' @field identifier  character 
#'
#' @field param  \link{Parameter} [optional]
#'
#' @field value  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
OptColumnMapping <- R6::R6Class(
  'OptColumnMapping',
  public = list(
    `identifier` = NULL,
    `param` = NULL,
    `value` = NULL,
    initialize = function(`identifier`, `param`=NULL, `value`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`identifier`)) {
        stopifnot(is.character(`identifier`), length(`identifier`) == 1)
        self$`identifier` <- `identifier`
      }
      if (!is.null(`param`)) {
        stopifnot(R6::is.R6(`param`))
        self$`param` <- `param`
      }
      if (!is.null(`value`)) {
        stopifnot(is.character(`value`), length(`value`) == 1)
        self$`value` <- `value`
      }
    },
    toJSON = function() {
      OptColumnMappingObject <- list()
      if (!is.null(self$`identifier`)) {
        OptColumnMappingObject[['identifier']] <-
          self$`identifier`
      }
      if (!is.null(self$`param`)) {
        OptColumnMappingObject[['param']] <-
          self$`param`$toJSON()
      }
      if (!is.null(self$`value`)) {
        OptColumnMappingObject[['value']] <-
          self$`value`
      }

      OptColumnMappingObject
    },
    fromJSON = function(OptColumnMappingJson) {
      OptColumnMappingObject <- jsonlite::fromJSON(OptColumnMappingJson)
      if (!is.null(OptColumnMappingObject$`identifier`)) {
        self$`identifier` <- OptColumnMappingObject$`identifier`
      }
      if (!is.null(OptColumnMappingObject$`param`)) {
        paramObject <- Parameter$new()
        paramObject$fromJSON(jsonlite::toJSON(OptColumnMappingObject$param, auto_unbox = TRUE, digits = NA))
        self$`param` <- paramObject
      }
      if (!is.null(OptColumnMappingObject$`value`)) {
        self$`value` <- OptColumnMappingObject$`value`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`identifier`)) {
        sprintf(
        '"identifier":
          "%s"
                ',
        self$`identifier`
        )},
        if (!is.null(self$`param`)) {
        sprintf(
        '"param":
        %s
        ',
        jsonlite::toJSON(self$`param`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`value`)) {
        sprintf(
        '"value":
          "%s"
                ',
        self$`value`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(OptColumnMappingJson) {
      OptColumnMappingObject <- jsonlite::fromJSON(OptColumnMappingJson)
      self$`identifier` <- OptColumnMappingObject$`identifier`
      self$`param` <- Parameter$new()$fromJSON(jsonlite::toJSON(OptColumnMappingObject$param, auto_unbox = TRUE, digits = NA))
      self$`value` <- OptColumnMappingObject$`value`
      self
    }
  )
)
