# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@isas.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Parameter
#' @description Parameter Class
#' @format An \code{R6Class} generator object
#' @field id  integer 
#'
#' @field elementType  character 
#'
#' @field cv_label  character [optional]
#'
#' @field cv_accession  character [optional]
#'
#' @field name  character 
#'
#' @field value  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Parameter <- R6::R6Class(
  'Parameter',
  public = list(
    `id` = NULL,
    `elementType` = NULL,
    `cv_label` = NULL,
    `cv_accession` = NULL,
    `name` = NULL,
    `value` = NULL,
    initialize = function(`id`, `elementType`, `name`, `value`, `cv_label`='', `cv_accession`='', ...){
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`elementType`)) {
        stopifnot(is.character(`elementType`), length(`elementType`) == 1)
        self$`elementType` <- `elementType`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`value`)) {
        stopifnot(is.character(`value`), length(`value`) == 1)
        self$`value` <- `value`
      }
      if (!is.null(`cv_label`)) {
        stopifnot(is.character(`cv_label`), length(`cv_label`) == 1)
        self$`cv_label` <- `cv_label`
      }
      if (!is.null(`cv_accession`)) {
        stopifnot(is.character(`cv_accession`), length(`cv_accession`) == 1)
        self$`cv_accession` <- `cv_accession`
      }
    },
    toJSON = function() {
      ParameterObject <- list()
      if (!is.null(self$`id`)) {
        ParameterObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`elementType`)) {
        ParameterObject[['elementType']] <-
          self$`elementType`
      }
      if (!is.null(self$`cv_label`)) {
        ParameterObject[['cv_label']] <-
          self$`cv_label`
      }
      if (!is.null(self$`cv_accession`)) {
        ParameterObject[['cv_accession']] <-
          self$`cv_accession`
      }
      if (!is.null(self$`name`)) {
        ParameterObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`value`)) {
        ParameterObject[['value']] <-
          self$`value`
      }

      ParameterObject
    },
    fromJSON = function(ParameterJson) {
      ParameterObject <- jsonlite::fromJSON(ParameterJson)
      if (!is.null(ParameterObject$`id`)) {
        self$`id` <- ParameterObject$`id`
      }
      if (!is.null(ParameterObject$`elementType`)) {
        self$`elementType` <- ParameterObject$`elementType`
      }
      if (!is.null(ParameterObject$`cv_label`)) {
        self$`cv_label` <- ParameterObject$`cv_label`
      }
      if (!is.null(ParameterObject$`cv_accession`)) {
        self$`cv_accession` <- ParameterObject$`cv_accession`
      }
      if (!is.null(ParameterObject$`name`)) {
        self$`name` <- ParameterObject$`name`
      }
      if (!is.null(ParameterObject$`value`)) {
        self$`value` <- ParameterObject$`value`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`elementType`)) {
        sprintf(
        '"elementType":
          "%s"
                ',
        self$`elementType`
        )},
        if (!is.null(self$`cv_label`)) {
        sprintf(
        '"cv_label":
          "%s"
                ',
        self$`cv_label`
        )},
        if (!is.null(self$`cv_accession`)) {
        sprintf(
        '"cv_accession":
          "%s"
                ',
        self$`cv_accession`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`value`)) {
        sprintf(
        '"value":
          "%s"
                ',
        self$`value`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ParameterJson) {
      ParameterObject <- jsonlite::fromJSON(ParameterJson)
      self$`id` <- ParameterObject$`id`
      self$`elementType` <- ParameterObject$`elementType`
      self$`cv_label` <- ParameterObject$`cv_label`
      self$`cv_accession` <- ParameterObject$`cv_accession`
      self$`name` <- ParameterObject$`name`
      self$`value` <- ParameterObject$`value`
      self
    }
  )
)
