# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@isas.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PublicationAllOf
#' @description PublicationAllOf Class
#' @format An \code{R6Class} generator object
#' @field publicationItems  list( \link{PublicationItem} ) 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PublicationAllOf <- R6::R6Class(
  'PublicationAllOf',
  public = list(
    `publicationItems` = NULL,
    initialize = function(`publicationItems`, ...){
      local.optional.var <- list(...)
      if (!missing(`publicationItems`)) {
        stopifnot(is.vector(`publicationItems`), length(`publicationItems`) != 0)
        sapply(`publicationItems`, function(x) stopifnot(R6::is.R6(x)))
        self$`publicationItems` <- `publicationItems`
      }
    },
    toJSON = function() {
      PublicationAllOfObject <- list()
      if (!is.null(self$`publicationItems`)) {
        PublicationAllOfObject[['publicationItems']] <-
          lapply(self$`publicationItems`, function(x) x$toJSON())
      }

      PublicationAllOfObject
    },
    fromJSON = function(PublicationAllOfJson) {
      PublicationAllOfObject <- jsonlite::fromJSON(PublicationAllOfJson)
      if (!is.null(PublicationAllOfObject$`publicationItems`)) {
        self$`publicationItems` <- ApiClient$new()$deserializeObj(PublicationAllOfObject$`publicationItems`, "array[PublicationItem]", loadNamespace("rmzTabM"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`publicationItems`)) {
        sprintf(
        '"publicationItems":
        [%s]
',
        paste(sapply(self$`publicationItems`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PublicationAllOfJson) {
      PublicationAllOfObject <- jsonlite::fromJSON(PublicationAllOfJson)
      self$`publicationItems` <- ApiClient$new()$deserializeObj(PublicationAllOfObject$`publicationItems`, "array[PublicationItem]", loadNamespace("rmzTabM"))
      self
    }
  )
)
