# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@isas.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Publication
#' @description Publication Class
#' @format An \code{R6Class} generator object
#' @field id  integer 
#'
#' @field elementType  character 
#'
#' @field publicationItems  list( \link{PublicationItem} ) 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Publication <- R6::R6Class(
  'Publication',
  public = list(
    `id` = NULL,
    `elementType` = NULL,
    `publicationItems` = NULL,
    initialize = function(`id`, `elementType`, `publicationItems`, ...){
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`elementType`)) {
        stopifnot(is.character(`elementType`), length(`elementType`) == 1)
        self$`elementType` <- `elementType`
      }
      if (!missing(`publicationItems`)) {
        stopifnot(is.vector(`publicationItems`), length(`publicationItems`) != 0)
        sapply(`publicationItems`, function(x) stopifnot(R6::is.R6(x)))
        self$`publicationItems` <- `publicationItems`
      }
    },
    toJSON = function() {
      PublicationObject <- list()
      if (!is.null(self$`id`)) {
        PublicationObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`elementType`)) {
        PublicationObject[['elementType']] <-
          self$`elementType`
      }
      if (!is.null(self$`publicationItems`)) {
        PublicationObject[['publicationItems']] <-
          lapply(self$`publicationItems`, function(x) x$toJSON())
      }

      PublicationObject
    },
    fromJSON = function(PublicationJson) {
      PublicationObject <- jsonlite::fromJSON(PublicationJson)
      if (!is.null(PublicationObject$`id`)) {
        self$`id` <- PublicationObject$`id`
      }
      if (!is.null(PublicationObject$`elementType`)) {
        self$`elementType` <- PublicationObject$`elementType`
      }
      if (!is.null(PublicationObject$`publicationItems`)) {
        self$`publicationItems` <- ApiClient$new()$deserializeObj(PublicationObject$`publicationItems`, "array[PublicationItem]", loadNamespace("rmzTabM"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`elementType`)) {
        sprintf(
        '"elementType":
          "%s"
                ',
        self$`elementType`
        )},
        if (!is.null(self$`publicationItems`)) {
        sprintf(
        '"publicationItems":
        [%s]
',
        paste(sapply(self$`publicationItems`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PublicationJson) {
      PublicationObject <- jsonlite::fromJSON(PublicationJson)
      self$`id` <- PublicationObject$`id`
      self$`elementType` <- PublicationObject$`elementType`
      self$`publicationItems` <- ApiClient$new()$deserializeObj(PublicationObject$`publicationItems`, "array[PublicationItem]", loadNamespace("rmzTabM"))
      self
    }
  )
)
