# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@isas.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SampleProcessing
#' @description SampleProcessing Class
#' @format An \code{R6Class} generator object
#' @field id  integer 
#'
#' @field elementType  character 
#'
#' @field sampleProcessing  list( \link{Parameter} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SampleProcessing <- R6::R6Class(
  'SampleProcessing',
  public = list(
    `id` = NULL,
    `elementType` = NULL,
    `sampleProcessing` = NULL,
    initialize = function(`id`, `elementType`, `sampleProcessing`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`elementType`)) {
        stopifnot(is.character(`elementType`), length(`elementType`) == 1)
        self$`elementType` <- `elementType`
      }
      if (!is.null(`sampleProcessing`)) {
        stopifnot(is.vector(`sampleProcessing`), length(`sampleProcessing`) != 0)
        sapply(`sampleProcessing`, function(x) stopifnot(R6::is.R6(x)))
        self$`sampleProcessing` <- `sampleProcessing`
      }
    },
    toJSON = function() {
      SampleProcessingObject <- list()
      if (!is.null(self$`id`)) {
        SampleProcessingObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`elementType`)) {
        SampleProcessingObject[['elementType']] <-
          self$`elementType`
      }
      if (!is.null(self$`sampleProcessing`)) {
        SampleProcessingObject[['sampleProcessing']] <-
          lapply(self$`sampleProcessing`, function(x) x$toJSON())
      }

      SampleProcessingObject
    },
    fromJSON = function(SampleProcessingJson) {
      SampleProcessingObject <- jsonlite::fromJSON(SampleProcessingJson)
      if (!is.null(SampleProcessingObject$`id`)) {
        self$`id` <- SampleProcessingObject$`id`
      }
      if (!is.null(SampleProcessingObject$`elementType`)) {
        self$`elementType` <- SampleProcessingObject$`elementType`
      }
      if (!is.null(SampleProcessingObject$`sampleProcessing`)) {
        self$`sampleProcessing` <- ApiClient$new()$deserializeObj(SampleProcessingObject$`sampleProcessing`, "array[Parameter]", loadNamespace("rmzTabM"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`elementType`)) {
        sprintf(
        '"elementType":
          "%s"
                ',
        self$`elementType`
        )},
        if (!is.null(self$`sampleProcessing`)) {
        sprintf(
        '"sampleProcessing":
        [%s]
',
        paste(sapply(self$`sampleProcessing`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SampleProcessingJson) {
      SampleProcessingObject <- jsonlite::fromJSON(SampleProcessingJson)
      self$`id` <- SampleProcessingObject$`id`
      self$`elementType` <- SampleProcessingObject$`elementType`
      self$`sampleProcessing` <- ApiClient$new()$deserializeObj(SampleProcessingObject$`sampleProcessing`, "array[Parameter]", loadNamespace("rmzTabM"))
      self
    }
  )
)
