# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@cebitec.uni-bielefeld.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SampleProcessing
#' @description SampleProcessing Class
#' @format An \code{R6Class} generator object
#' @field id  integer [optional]
#'
#' @field sampleProcessing  list( \link{Parameter} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SampleProcessing <- R6::R6Class(
  'SampleProcessing',
  public = list(
    `id` = NULL,
    `sampleProcessing` = NULL,
    #' @description Create a SampleProcessing object
    #' @param id SampleProcessing id.
    #' @param sampleProcessing Sample processing list( \link{Parameter} ).
    #' @param ... local optional variable arguments
    #'     
    initialize = function(`id`=NULL, `sampleProcessing`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`sampleProcessing`)) {
        stopifnot(is.vector(`sampleProcessing`), length(`sampleProcessing`) != 0)
        sapply(`sampleProcessing`, function(x) stopifnot(R6::is.R6(x)))
        self$`sampleProcessing` <- `sampleProcessing`
      }
    },
    #' @description Serialize to list object suitable for jsonlite
    toJSON = function() {
      SampleProcessingObject <- list()
      if (!is.null(self$`id`)) {
        SampleProcessingObject[['id']] <-
          rmzTabM::safe_unbox(self$`id`)
      }
      if (!is.null(self$`sampleProcessing`)) {
        SampleProcessingObject[['sampleProcessing']] <-
          lapply(self$`sampleProcessing`, function(x) x$toJSON())
      }

      SampleProcessingObject
    },
    #' @description Deserialize from jsonlite list object
    #' @param SampleProcessingJson list object.
    fromJSON = function(SampleProcessingJson) {
      SampleProcessingObject <- jsonlite::fromJSON(SampleProcessingJson)
      if (!is.null(SampleProcessingObject$`id`)) {
        self$`id` <- SampleProcessingObject$`id`
      }
      if (!is.null(SampleProcessingObject$`sampleProcessing`)) {
        self$`sampleProcessing` <- ApiClient$new()$deserializeObj(SampleProcessingObject$`sampleProcessing`, "array[Parameter]", loadNamespace("rmzTabM"))
      }
    },
    #' @description Serialize to JSON string.
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        rmzTabM::safe_unbox(self$`id`)
        )},
        if (!is.null(self$`sampleProcessing`)) {
        sprintf(
        '"sampleProcessing":
        [%s]
',
        paste(sapply(self$`sampleProcessing`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=FALSE, null = "null", na = "null", digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    #' @description Deserialize from JSON string
    #' @param SampleProcessingJson JSON string
    fromJSONString = function(SampleProcessingJson) {
      SampleProcessingObject <- jsonlite::fromJSON(SampleProcessingJson)
      self$`id` <- SampleProcessingObject$`id`
      self$`sampleProcessing` <- ApiClient$new()$deserializeObj(SampleProcessingObject$`sampleProcessing`, "array[Parameter]", loadNamespace("rmzTabM"))
      self
    },
    #' @description Serialize to data frame
    toDataFrame = function() {
      idPrefix <- paste0("sample_processing[", self$`id`, "]")
      elements <- data.frame(PREFIX=character(), KEY=character(), VALUE=character())
      if (!is.null(self$`sampleProcessing`)) {
        elements <-
          rbind(elements,
                list(PREFIX = "MTD",
                     KEY = idPrefix,
                     VALUE = paste(lapply(self$`sampleProcessing`, function(x) x$toString()), collapse="|")), 
                stringsAsFactors = FALSE)
      }
      elements
    },
    #' @description Deserialize from SampleProcessingDataFrame
    #' @param SampleProcessingDataFrame Sample processing data frame
    fromDataFrame = function(SampleProcessingDataFrame) {
      stopifnot(nrow(SampleProcessingDataFrame)==1)
      if (rlang::has_name(SampleProcessingDataFrame, "id")) {
        self$`id` <- as.numeric(SampleProcessingDataFrame$`id`)
      }
      if (rlang::has_name(SampleProcessingDataFrame, "param")) {
        self$`sampleProcessing` <- lapply(splitList(SampleProcessingDataFrame$`param`), function(x) {
          param <- Parameter$new()
          param$fromString(NULL, x)
        })
      }
      self
    }
  )
)
