# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@isas.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Software
#' @description Software Class
#' @format An \code{R6Class} generator object
#' @field id  integer [optional]
#'
#' @field parameter  \link{Parameter} [optional]
#'
#' @field setting  list( character ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Software <- R6::R6Class(
  'Software',
  public = list(
    `id` = NULL,
    `parameter` = NULL,
    `setting` = NULL,
    initialize = function(`id`=NULL, `parameter`=NULL, `setting`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`parameter`)) {
        stopifnot(R6::is.R6(`parameter`))
        self$`parameter` <- `parameter`
      }
      if (!is.null(`setting`)) {
        stopifnot(is.vector(`setting`), length(`setting`) != 0)
        sapply(`setting`, function(x) stopifnot(is.character(x)))
        self$`setting` <- `setting`
      }
    },
    toJSON = function() {
      SoftwareObject <- list()
      if (!is.null(self$`id`)) {
        SoftwareObject[['id']] <-
          jsonlite::unbox(self$`id`)
      }
      if (!is.null(self$`parameter`)) {
        SoftwareObject[['parameter']] <-
          self$`parameter`$toJSON()
      }
      if (!is.null(self$`setting`)) {
        SoftwareObject[['setting']] <-
          unlist(self$`setting`)
      }

      SoftwareObject
    },
    fromJSON = function(SoftwareJson) {
      SoftwareObject <- jsonlite::fromJSON(SoftwareJson)
      if (!is.null(SoftwareObject$`id`)) {
        self$`id` <- SoftwareObject$`id`
      }
      if (!is.null(SoftwareObject$`parameter`)) {
        parameterObject <- Parameter$new()
        parameterObject$fromJSON(jsonlite::toJSON(SoftwareObject$parameter, auto_unbox = TRUE, null = "null", na = "null", digits = NA))
        self$`parameter` <- parameterObject
      }
      if (!is.null(SoftwareObject$`setting`)) {
        self$`setting` <- ApiClient$new()$deserializeObj(SoftwareObject$`setting`, "array[character]", loadNamespace("rmzTabM"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        jsonlite::unbox(self$`id`)
        )},
        if (!is.null(self$`parameter`)) {
        sprintf(
        '"parameter":
        %s
        ',
        jsonlite::toJSON(self$`parameter`$toJSON(), auto_unbox=FALSE, null = "null", na = "null", digits = NA)
        )},
        if (!is.null(self$`setting`)) {
        sprintf(
        '"setting":
           %s
        ',
        jsonlite::toJSON(unlist(self$`setting`), auto_unbox = FALSE, null = "null", na = "null", digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SoftwareJson) {
      SoftwareObject <- jsonlite::fromJSON(SoftwareJson)
      self$`id` <- SoftwareObject$`id`
      self$`parameter` <- Parameter$new()$fromJSONString(jsonlite::toJSON(SoftwareObject$parameter, auto_unbox = TRUE, null = "null", na = "null", digits = NA))
      self$`setting` <- ApiClient$new()$deserializeObj(SoftwareObject$`setting`, "array[character]", loadNamespace("rmzTabM"))
      self
    }
  )
)
