# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@isas.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SoftwareAllOf
#' @description SoftwareAllOf Class
#' @format An \code{R6Class} generator object
#' @field parameter  \link{Parameter} [optional]
#'
#' @field setting  list( character ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SoftwareAllOf <- R6::R6Class(
  'SoftwareAllOf',
  public = list(
    `parameter` = NULL,
    `setting` = NULL,
    initialize = function(`parameter`=NULL, `setting`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`parameter`)) {
        stopifnot(R6::is.R6(`parameter`))
        self$`parameter` <- `parameter`
      }
      if (!is.null(`setting`)) {
        stopifnot(is.vector(`setting`), length(`setting`) != 0)
        sapply(`setting`, function(x) stopifnot(is.character(x)))
        self$`setting` <- `setting`
      }
    },
    toJSON = function() {
      SoftwareAllOfObject <- list()
      if (!is.null(self$`parameter`)) {
        SoftwareAllOfObject[['parameter']] <-
          self$`parameter`$toJSON()
      }
      if (!is.null(self$`setting`)) {
        SoftwareAllOfObject[['setting']] <-
          self$`setting`
      }

      SoftwareAllOfObject
    },
    fromJSON = function(SoftwareAllOfJson) {
      SoftwareAllOfObject <- jsonlite::fromJSON(SoftwareAllOfJson)
      if (!is.null(SoftwareAllOfObject$`parameter`)) {
        parameterObject <- Parameter$new()
        parameterObject$fromJSON(jsonlite::toJSON(SoftwareAllOfObject$parameter, auto_unbox = TRUE, digits = NA))
        self$`parameter` <- parameterObject
      }
      if (!is.null(SoftwareAllOfObject$`setting`)) {
        self$`setting` <- ApiClient$new()$deserializeObj(SoftwareAllOfObject$`setting`, "array[character]", loadNamespace("rmzTabM"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`parameter`)) {
        sprintf(
        '"parameter":
        %s
        ',
        jsonlite::toJSON(self$`parameter`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`setting`)) {
        sprintf(
        '"setting":
           [%s]
        ',
        paste(unlist(lapply(self$`setting`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SoftwareAllOfJson) {
      SoftwareAllOfObject <- jsonlite::fromJSON(SoftwareAllOfJson)
      self$`parameter` <- Parameter$new()$fromJSON(jsonlite::toJSON(SoftwareAllOfObject$parameter, auto_unbox = TRUE, digits = NA))
      self$`setting` <- ApiClient$new()$deserializeObj(SoftwareAllOfObject$`setting`, "array[character]", loadNamespace("rmzTabM"))
      self
    }
  )
)
