# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@isas.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SpectraRef
#' @description SpectraRef Class
#' @format An \code{R6Class} generator object
#' @field ms_run  \link{MsRun} 
#'
#' @field reference  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SpectraRef <- R6::R6Class(
  'SpectraRef',
  public = list(
    `ms_run` = NULL,
    `reference` = NULL,
    initialize = function(`ms_run`, `reference`, ...){
      local.optional.var <- list(...)
      if (!missing(`ms_run`)) {
        stopifnot(R6::is.R6(`ms_run`))
        self$`ms_run` <- `ms_run`
      }
      if (!missing(`reference`)) {
        stopifnot(is.character(`reference`), length(`reference`) == 1)
        self$`reference` <- `reference`
      }
    },
    toJSON = function() {
      SpectraRefObject <- list()
      if (!is.null(self$`ms_run`)) {
        SpectraRefObject[['ms_run']] <-
          self$`ms_run`$toJSON()
      }
      if (!is.null(self$`reference`)) {
        SpectraRefObject[['reference']] <-
          self$`reference`
      }

      SpectraRefObject
    },
    fromJSON = function(SpectraRefJson) {
      SpectraRefObject <- jsonlite::fromJSON(SpectraRefJson)
      if (!is.null(SpectraRefObject$`ms_run`)) {
        ms_runObject <- MsRun$new()
        ms_runObject$fromJSON(jsonlite::toJSON(SpectraRefObject$ms_run, auto_unbox = TRUE, digits = NA))
        self$`ms_run` <- ms_runObject
      }
      if (!is.null(SpectraRefObject$`reference`)) {
        self$`reference` <- SpectraRefObject$`reference`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`ms_run`)) {
        sprintf(
        '"ms_run":
        %s
        ',
        jsonlite::toJSON(self$`ms_run`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`reference`)) {
        sprintf(
        '"reference":
          "%s"
                ',
        self$`reference`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SpectraRefJson) {
      SpectraRefObject <- jsonlite::fromJSON(SpectraRefJson)
      self$`ms_run` <- MsRun$new()$fromJSON(jsonlite::toJSON(SpectraRefObject$ms_run, auto_unbox = TRUE, digits = NA))
      self$`reference` <- SpectraRefObject$`reference`
      self
    }
  )
)
