# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@isas.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title StudyVariableAllOf
#' @description StudyVariableAllOf Class
#' @format An \code{R6Class} generator object
#' @field name  character 
#'
#' @field assay_refs  list( \link{Assay} ) [optional]
#'
#' @field average_function  \link{Parameter} [optional]
#'
#' @field variation_function  \link{Parameter} [optional]
#'
#' @field description  character [optional]
#'
#' @field factors  list( \link{Parameter} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StudyVariableAllOf <- R6::R6Class(
  'StudyVariableAllOf',
  public = list(
    `name` = NULL,
    `assay_refs` = NULL,
    `average_function` = NULL,
    `variation_function` = NULL,
    `description` = NULL,
    `factors` = NULL,
    initialize = function(`name`, `assay_refs`=NULL, `average_function`=NULL, `variation_function`=NULL, `description`=NULL, `factors`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`assay_refs`)) {
        stopifnot(is.vector(`assay_refs`), length(`assay_refs`) != 0)
        sapply(`assay_refs`, function(x) stopifnot(R6::is.R6(x)))
        self$`assay_refs` <- `assay_refs`
      }
      if (!is.null(`average_function`)) {
        stopifnot(R6::is.R6(`average_function`))
        self$`average_function` <- `average_function`
      }
      if (!is.null(`variation_function`)) {
        stopifnot(R6::is.R6(`variation_function`))
        self$`variation_function` <- `variation_function`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`factors`)) {
        stopifnot(is.vector(`factors`), length(`factors`) != 0)
        sapply(`factors`, function(x) stopifnot(R6::is.R6(x)))
        self$`factors` <- `factors`
      }
    },
    toJSON = function() {
      StudyVariableAllOfObject <- list()
      if (!is.null(self$`name`)) {
        StudyVariableAllOfObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`assay_refs`)) {
        StudyVariableAllOfObject[['assay_refs']] <-
          lapply(self$`assay_refs`, function(x) x$toJSON())
      }
      if (!is.null(self$`average_function`)) {
        StudyVariableAllOfObject[['average_function']] <-
          self$`average_function`$toJSON()
      }
      if (!is.null(self$`variation_function`)) {
        StudyVariableAllOfObject[['variation_function']] <-
          self$`variation_function`$toJSON()
      }
      if (!is.null(self$`description`)) {
        StudyVariableAllOfObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`factors`)) {
        StudyVariableAllOfObject[['factors']] <-
          lapply(self$`factors`, function(x) x$toJSON())
      }

      StudyVariableAllOfObject
    },
    fromJSON = function(StudyVariableAllOfJson) {
      StudyVariableAllOfObject <- jsonlite::fromJSON(StudyVariableAllOfJson)
      if (!is.null(StudyVariableAllOfObject$`name`)) {
        self$`name` <- StudyVariableAllOfObject$`name`
      }
      if (!is.null(StudyVariableAllOfObject$`assay_refs`)) {
        self$`assay_refs` <- ApiClient$new()$deserializeObj(StudyVariableAllOfObject$`assay_refs`, "array[Assay]", loadNamespace("rmzTabM"))
      }
      if (!is.null(StudyVariableAllOfObject$`average_function`)) {
        average_functionObject <- Parameter$new()
        average_functionObject$fromJSON(jsonlite::toJSON(StudyVariableAllOfObject$average_function, auto_unbox = TRUE, digits = NA))
        self$`average_function` <- average_functionObject
      }
      if (!is.null(StudyVariableAllOfObject$`variation_function`)) {
        variation_functionObject <- Parameter$new()
        variation_functionObject$fromJSON(jsonlite::toJSON(StudyVariableAllOfObject$variation_function, auto_unbox = TRUE, digits = NA))
        self$`variation_function` <- variation_functionObject
      }
      if (!is.null(StudyVariableAllOfObject$`description`)) {
        self$`description` <- StudyVariableAllOfObject$`description`
      }
      if (!is.null(StudyVariableAllOfObject$`factors`)) {
        self$`factors` <- ApiClient$new()$deserializeObj(StudyVariableAllOfObject$`factors`, "array[Parameter]", loadNamespace("rmzTabM"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`assay_refs`)) {
        sprintf(
        '"assay_refs":
        [%s]
',
        paste(sapply(self$`assay_refs`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`average_function`)) {
        sprintf(
        '"average_function":
        %s
        ',
        jsonlite::toJSON(self$`average_function`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`variation_function`)) {
        sprintf(
        '"variation_function":
        %s
        ',
        jsonlite::toJSON(self$`variation_function`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`factors`)) {
        sprintf(
        '"factors":
        [%s]
',
        paste(sapply(self$`factors`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StudyVariableAllOfJson) {
      StudyVariableAllOfObject <- jsonlite::fromJSON(StudyVariableAllOfJson)
      self$`name` <- StudyVariableAllOfObject$`name`
      self$`assay_refs` <- ApiClient$new()$deserializeObj(StudyVariableAllOfObject$`assay_refs`, "array[Assay]", loadNamespace("rmzTabM"))
      self$`average_function` <- Parameter$new()$fromJSON(jsonlite::toJSON(StudyVariableAllOfObject$average_function, auto_unbox = TRUE, digits = NA))
      self$`variation_function` <- Parameter$new()$fromJSON(jsonlite::toJSON(StudyVariableAllOfObject$variation_function, auto_unbox = TRUE, digits = NA))
      self$`description` <- StudyVariableAllOfObject$`description`
      self$`factors` <- ApiClient$new()$deserializeObj(StudyVariableAllOfObject$`factors`, "array[Parameter]", loadNamespace("rmzTabM"))
      self
    }
  )
)
