# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@cebitec.uni-bielefeld.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title StudyVariable
#' @description StudyVariable Class
#' @format An \code{R6Class} generator object
#' @field id  integer 
#'
#' @field name  character 
#'
#' @field assay_refs  list( \link{Assay} ) [optional]
#'
#' @field average_function  \link{Parameter} [optional]
#'
#' @field variation_function  \link{Parameter} [optional]
#'
#' @field description  character [optional]
#'
#' @field factors  list( \link{Parameter} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StudyVariable <- R6::R6Class(
  'StudyVariable',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `assay_refs` = NULL,
    `average_function` = NULL,
    `variation_function` = NULL,
    `description` = NULL,
    `factors` = NULL,
    #' @description Create a StudyVariable
    #' @param id StudyVariable id.
    #' @param name StudyVariable name.
    #' @param assay_refs Reference to list( \link{Assay} ).
    #' @param average_function The averaging function used to calculate abundance_study_variable, defined by \link{Parameter}.
    #' @param variation_function The variation function used to calculate abundance_variation_study_variable, defined by \link{Parameter}.
    #' @param description Description of the StudyVariable.
    #' @param factors A list of study variable factors list( \link{Parameter} ).
    #' @param ... local optional variable arguments
    #' 
    initialize = function(`id`, `name`, `assay_refs`=NULL, `average_function`=NULL, `variation_function`=NULL, `description`=NULL, `factors`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`assay_refs`)) {
        stopifnot(is.vector(`assay_refs`), length(`assay_refs`) != 0)
        sapply(`assay_refs`, function(x) stopifnot(is.numeric(x)))
        self$`assay_refs` <- `assay_refs`
      }
      if (!is.null(`average_function`)) {
        stopifnot(R6::is.R6(`average_function`))
        self$`average_function` <- `average_function`
      }
      if (!is.null(`variation_function`)) {
        stopifnot(R6::is.R6(`variation_function`))
        self$`variation_function` <- `variation_function`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`factors`)) {
        stopifnot(is.vector(`factors`), length(`factors`) != 0)
        sapply(`factors`, function(x) stopifnot(R6::is.R6(x)))
        self$`factors` <- `factors`
      }
    },
    #' @description Serialize to list object suitable for jsonlite
    toJSON = function() {
      StudyVariableObject <- list()
      if (!is.null(self$`id`)) {
        StudyVariableObject[['id']] <-
          rmzTabM::safe_unbox(self$`id`)
      }
      if (!is.null(self$`name`)) {
        StudyVariableObject[['name']] <-
          rmzTabM::safe_unbox(self$`name`)
      }
      if (!is.null(self$`assay_refs`)) {
        StudyVariableObject[['assay_refs']] <-
          rmzTabM::safe_unbox(self$`assay_refs`)
      }
      if (!is.null(self$`average_function`)) {
        StudyVariableObject[['average_function']] <-
          self$`average_function`$toJSON()
      }
      if (!is.null(self$`variation_function`)) {
        StudyVariableObject[['variation_function']] <-
          self$`variation_function`$toJSON()
      }
      if (!is.null(self$`description`)) {
        StudyVariableObject[['description']] <-
          rmzTabM::safe_unbox(self$`description`)
      }
      if (!is.null(self$`factors`)) {
        StudyVariableObject[['factors']] <-
          lapply(self$`factors`, function(x) x$toJSON())
      }

      StudyVariableObject
    },
    #' @description Deserialize from jsonlite list object
    #' @param StudyVariableJson list object.
    fromJSON = function(StudyVariableJson) {
      StudyVariableObject <- jsonlite::fromJSON(StudyVariableJson)
      if (!is.null(StudyVariableObject$`id`)) {
        self$`id` <- StudyVariableObject$`id`
      }
      if (!is.null(StudyVariableObject$`name`)) {
        self$`name` <- StudyVariableObject$`name`
      }
      if (!is.null(StudyVariableObject$`assay_refs`)) {
        self$`assay_refs` <- ApiClient$new()$deserializeObj(StudyVariableObject$`assay_refs`, "array[integer]", loadNamespace("rmzTabM"))
      }
      if (!is.null(StudyVariableObject$`average_function`)) {
        average_functionObject <- Parameter$new()
        average_functionObject$fromJSON(jsonlite::toJSON(StudyVariableObject$average_function, auto_unbox = TRUE, null = "null", na = "null", digits = NA))
        self$`average_function` <- average_functionObject
      }
      if (!is.null(StudyVariableObject$`variation_function`)) {
        variation_functionObject <- Parameter$new()
        variation_functionObject$fromJSON(jsonlite::toJSON(StudyVariableObject$variation_function, auto_unbox = TRUE, null = "null", na = "null", digits = NA))
        self$`variation_function` <- variation_functionObject
      }
      if (!is.null(StudyVariableObject$`description`)) {
        self$`description` <- StudyVariableObject$`description`
      }
      if (!is.null(StudyVariableObject$`factors`)) {
        self$`factors` <- ApiClient$new()$deserializeObj(StudyVariableObject$`factors`, "array[Parameter]", loadNamespace("rmzTabM"))
      }
    },
    #' @description Serialize to JSON string.
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        rmzTabM::safe_unbox(self$`id`)
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        rmzTabM::safe_unbox(self$`name`)
        )},
        if (!is.null(self$`assay_refs`)) {
        sprintf(
        '"assay_refs":
        [%s]
',
        paste(unlist(lapply(self$`assay_refs`, function(x) paste0(x))), collapse=",")
        )},
        if (!is.null(self$`average_function`)) {
        sprintf(
        '"average_function":
        %s
        ',
        jsonlite::toJSON(self$`average_function`$toJSON(), auto_unbox=FALSE, null = "null", na = "null", digits = NA)
        )},
        if (!is.null(self$`variation_function`)) {
        sprintf(
        '"variation_function":
        %s
        ',
        jsonlite::toJSON(self$`variation_function`$toJSON(), auto_unbox=FALSE, null = "null", na = "null", digits = NA)
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        rmzTabM::safe_unbox(self$`description`)
        )},
        if (!is.null(self$`factors`)) {
        sprintf(
        '"factors":
        %s
',
        paste(sapply(self$`factors`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=FALSE, null = "null", na = "null", digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    #' @description Deserialize from JSON string
    #' @param StudyVariableJson JSON string
    fromJSONString = function(StudyVariableJson) {
      StudyVariableObject <- jsonlite::fromJSON(StudyVariableJson)
      self$`id` <- StudyVariableObject$`id`
      self$`name` <- StudyVariableObject$`name`
      self$`assay_refs` <- StudyVariableObject$`assay_refs`
      self$`average_function` <- Parameter$new()$fromJSONString(jsonlite::toJSON(StudyVariableObject$average_function, auto_unbox = TRUE, null = "null", na = "null", digits = NA))
      self$`variation_function` <- Parameter$new()$fromJSONString(jsonlite::toJSON(StudyVariableObject$variation_function, auto_unbox = TRUE, null = "null", na = "null", digits = NA))
      self$`description` <- StudyVariableObject$`description`
      self$`factors` <- ApiClient$new()$deserializeObj(StudyVariableObject$`factors`, "array[Parameter]", loadNamespace("rmzTabM"))
      self
    },
    #' @description Serialize to data frame    
    toDataFrame = function() {
      idPrefix <- paste0("study_variable[", self$`id`, "]")
      elements <- data.frame(PREFIX=character(), KEY=character(), VALUE=character())
      if (!is.null(self$`name`)) {
        elements <-
          rbind(elements,
                list(
                  PREFIX = "MTD",
                  KEY = idPrefix,
                  VALUE = self$`name`
                ),
                stringsAsFactors = FALSE)
      }
      if (!is.null(self$`assay_refs`)) {
        elements <-
          rbind(elements,
                list(
                  PREFIX = "MTD",
                  KEY = paste(idPrefix, "assay_refs", sep = "-"),
                  VALUE = paste(lapply(self$`assay_refs`, function(x) paste0("assay[", x, "]")), collapse="|")
                ), 
                stringsAsFactors = FALSE)
      }
      if (!is.null(self$`average_function`)) {
        elements <-
          rbind(elements,
                list(
                  PREFIX = "MTD",
                  KEY = paste(idPrefix, "average_function", sep = "-"),
                  VALUE = self$`average_function`$toString()
                ),
                stringsAsFactors = FALSE)
      }
      if (!is.null(self$`variation_function`)) {
        elements <-
          rbind(elements,
                list(
                  PREFIX = "MTD",
                  KEY = paste(idPrefix, "variation_function", sep = "-"),
                  VALUE = self$`variation_function`$toString()
                ),
                stringsAsFactors = FALSE)
      }
      if (!is.null(self$`description`)) {
        elements <-
          rbind(elements,
                list(
                  PREFIX = "MTD",
                  KEY = paste(idPrefix, "description", sep = "-"),
                  VALUE = self$`description`
                ),
                stringsAsFactors = FALSE)
      }
      if (!is.null(self$`factors`)) {
        elements <-
          rbind(elements,
                lapply(seq_along(self$`factors`), function(idx, elements, idPrefix) {
                  list(PREFIX = "MTD", KEY=paste(idPrefix, paste0("factors[", idx, "]"), sep="-"), VALUE=elements[[idx]]$toString())
                }, elements=self$`factors`, idPrefix=idPrefix) %>% dplyr::bind_rows(),
                stringsAsFactors = FALSE)
      }
      elements
    },
    #' @description Deserialize from StudyVariable data frame
    #' @param StudyVariableDataFrame StudyVariable data frame    
    fromDataFrame = function(StudyVariableDataFrame) {
      stopifnot(nrow(StudyVariableDataFrame)==1)
      if (rlang::has_name(StudyVariableDataFrame, "id")) {
        self$`id` <- as.numeric(StudyVariableDataFrame$`id`)
      }
      if (rlang::has_name(StudyVariableDataFrame, "name")) {
        self$`name` <- StudyVariableDataFrame$`name`
      }
      if (rlang::has_name(StudyVariableDataFrame, "assay_refs")) { # list of references
        assayRefList <- splitList(StudyVariableDataFrame$`assay_refs`)
        self$`assay_refs` <- unlist(lapply(assayRefList, function(x) {
          extractId(x)  
        }))
      }
      if (rlang::has_name(StudyVariableDataFrame, "average_function")) {
        param <- Parameter$new()
        self$`average_function` <- param$fromString(NULL, StudyVariableDataFrame$`average_function`)
      }
      if (rlang::has_name(StudyVariableDataFrame, "variation_function")) {
        param <- Parameter$new()
        self$`variation_function` <- param$fromString(NULL, StudyVariableDataFrame$`variation_function`)
      }
      if (rlang::has_name(StudyVariableDataFrame, "description")) {
        self$`description` <- StudyVariableDataFrame$`description`
      }
      if (rlang::has_name(StudyVariableDataFrame, "factors")) {
        factorsList <- splitList(StudyVariableDataFrame$`factors`)
        self$`factors` <- unlist(lapply(factorsList, function(x) {
          param <- Parameter$new()
          param$fromString(NULL, x)
          param
        }))
      }
      self
    }
  )
)
