# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@cebitec.uni-bielefeld.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Uri
#' @description Uri Class
#' @format An \code{R6Class} generator object
#' @field id  integer [optional]
#'
#' @field value  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Uri <- R6::R6Class(
  'Uri',
  public = list(
    `id` = NULL,
    `value` = NULL,
    initialize = function(`id`=NULL, `value`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`value`)) {
        stopifnot(is.character(`value`), length(`value`) == 1)
        self$`value` <- `value`
      }
    },
    toJSON = function() {
      UriObject <- list()
      if (!is.null(self$`id`)) {
        UriObject[['id']] <-
           rmzTabM::safe_unbox(self$`id`)
      }
      if (!is.null(self$`value`)) {
        UriObject[['value']] <-
           rmzTabM::safe_unbox(self$`value`)
      }

      UriObject
    },
    fromJSON = function(UriJson) {
      UriObject <- jsonlite::fromJSON(UriJson)
      if (!is.null(UriObject$`id`)) {
        self$`id` <- UriObject$`id`
      }
      if (!is.null(UriObject$`value`)) {
        self$`value` <- UriObject$`value`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
         rmzTabM::safe_unbox(self$`id`)
        )},
        if (!is.null(self$`value`)) {
        sprintf(
        '"value":
          "%s"
                ',
         rmzTabM::safe_unbox(self$`value`)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(UriJson) {
      UriObject <- jsonlite::fromJSON(UriJson)
      self$`id` <- UriObject$`id`
      self$`value` <- UriObject$`value`
      self
    },
    toDataFrame = function(type="uri") {
      idPrefix <- paste0(type, "[", self$`id`, "]")
      elements <- data.frame(PREFIX=character(), KEY=character(), VALUE=character())
      if (!is.null(self$`value`)) {
        elements <-
          rbind(elements,
                list(
                  PREFIX = "MTD",
                  KEY = idPrefix,
                  VALUE = self$`value`
                ),
                stringsAsFactors = FALSE)
      }
    },
    fromDataFrame = function(UriDataFrame) {
      stopifnot(nrow(UriDataFrame)==1)
      if (rlang::has_name(UriDataFrame, "id")) {
        self$`id` <- as.numeric(UriDataFrame$`id`)
      }
      if (rlang::has_name(UriDataFrame, "value")) {
        self$`value` <- UriDataFrame$`value`
      }
      self
    }
  )
)
