# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@isas.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title UriAllOf
#' @description UriAllOf Class
#' @format An \code{R6Class} generator object
#' @field value  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UriAllOf <- R6::R6Class(
  'UriAllOf',
  public = list(
    `value` = NULL,
    initialize = function(`value`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`value`)) {
        stopifnot(is.character(`value`), length(`value`) == 1)
        self$`value` <- `value`
      }
    },
    toJSON = function() {
      UriAllOfObject <- list()
      if (!is.null(self$`value`)) {
        UriAllOfObject[['value']] <-
          self$`value`
      }

      UriAllOfObject
    },
    fromJSON = function(UriAllOfJson) {
      UriAllOfObject <- jsonlite::fromJSON(UriAllOfJson)
      if (!is.null(UriAllOfObject$`value`)) {
        self$`value` <- UriAllOfObject$`value`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`value`)) {
        sprintf(
        '"value":
          "%s"
                ',
        self$`value`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(UriAllOfJson) {
      UriAllOfObject <- jsonlite::fromJSON(UriAllOfJson)
      self$`value` <- UriAllOfObject$`value`
      self
    }
  )
)
