# mzTab-M reference implementation and validation API.
#
# This is the mzTab-M reference implementation and validation API service.
#
# The version of the OpenAPI document: 2.0.0
# Contact: nils.hoffmann@isas.de
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ValidationMessage
#' @description ValidationMessage Class
#' @format An \code{R6Class} generator object
#' @field code  character 
#'
#' @field category  character 
#'
#' @field message_type  character [optional]
#'
#' @field message  character 
#'
#' @field line_number  integer [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ValidationMessage <- R6::R6Class(
  'ValidationMessage',
  public = list(
    `code` = NULL,
    `category` = NULL,
    `message_type` = NULL,
    `message` = NULL,
    `line_number` = NULL,
    initialize = function(`code`, `category`, `message`, `message_type`='info', `line_number`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`code`)) {
        stopifnot(is.character(`code`), length(`code`) == 1)
        self$`code` <- `code`
      }
      if (!missing(`category`)) {
        stopifnot(is.character(`category`), length(`category`) == 1)
        self$`category` <- `category`
      }
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!is.null(`message_type`)) {
        stopifnot(is.character(`message_type`), length(`message_type`) == 1)
        self$`message_type` <- `message_type`
      }
      if (!is.null(`line_number`)) {
        stopifnot(is.numeric(`line_number`), length(`line_number`) == 1)
        self$`line_number` <- `line_number`
      }
    },
    toJSON = function() {
      ValidationMessageObject <- list()
      if (!is.null(self$`code`)) {
        ValidationMessageObject[['code']] <-
          rmzTabM::safe_unbox(self$`code`)
      }
      if (!is.null(self$`category`)) {
        ValidationMessageObject[['category']] <-
          rmzTabM::safe_unbox(self$`category`)
      }
      if (!is.null(self$`message_type`)) {
        ValidationMessageObject[['message_type']] <-
          rmzTabM::safe_unbox(self$`message_type`)
      }
      if (!is.null(self$`message`)) {
        ValidationMessageObject[['message']] <-
          rmzTabM::safe_unbox(self$`message`)
      }
      if (!is.null(self$`line_number`)) {
        ValidationMessageObject[['line_number']] <-
          rmzTabM::safe_unbox(self$`line_number`)
      }

      ValidationMessageObject
    },
    fromJSON = function(ValidationMessageJson) {
      ValidationMessageObject <- jsonlite::fromJSON(ValidationMessageJson)
      if (!is.null(ValidationMessageObject$`code`)) {
        self$`code` <- ValidationMessageObject$`code`
      }
      if (!is.null(ValidationMessageObject$`category`)) {
        self$`category` <- ValidationMessageObject$`category`
      }
      if (!is.null(ValidationMessageObject$`message_type`)) {
        self$`message_type` <- ValidationMessageObject$`message_type`
      }
      if (!is.null(ValidationMessageObject$`message`)) {
        self$`message` <- ValidationMessageObject$`message`
      }
      if (!is.null(ValidationMessageObject$`line_number`)) {
        self$`line_number` <- ValidationMessageObject$`line_number`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`code`)) {
        sprintf(
        '"code":
          "%s"
                ',
        rmzTabM::safe_unbox(self$`code`)
        )},
        if (!is.null(self$`category`)) {
        sprintf(
        '"category":
          "%s"
                ',
        rmzTabM::safe_unbox(self$`category`)
        )},
        if (!is.null(self$`message_type`)) {
        sprintf(
        '"message_type":
          "%s"
                ',
        rmzTabM::safe_unbox(self$`message_type`)
        )},
        if (!is.null(self$`message`)) {
        sprintf(
        '"message":
          "%s"
                ',
        rmzTabM::safe_unbox(self$`message`)
        )},
        if (!is.null(self$`line_number`)) {
        sprintf(
        '"line_number":
          %d
                ',
        rmzTabM::safe_unbox(self$`line_number`)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ValidationMessageJson) {
      ValidationMessageObject <- jsonlite::fromJSON(ValidationMessageJson)
      self$`code` <- ValidationMessageObject$`code`
      self$`category` <- ValidationMessageObject$`category`
      self$`message_type` <- ValidationMessageObject$`message_type`
      self$`message` <- ValidationMessageObject$`message`
      self$`line_number` <- ValidationMessageObject$`line_number`
      self
    }
  )
)
